---
- name: "Post-tasks | Update distro"
  become: true
  block:
    - name: "Post-tasks | Upgrade packages to latest version"
      community.general.pacman:
        upgrade: true
        state: "latest"
        update_cache: true

    - name: "Post-tasks | Clean cache of downloaded packages"
      ansible.builtin.shell:
        cmd: "echo -e 'y\ny\n' | pacman -Scc"
