---
- name: "Post-tasks | Always run tasks that are OS specific"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: always
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: always
