---
- name: "Post-tasks | Ensure that we do not wait for Network at startup"
  become: true
  ansible.builtin.systemd:
    name: "NetworkManager-wait-online"
    enabled: false
    scope: "system"
  tags: always
  when: ansible_facts.service_mgr == "systemd"

- name: "Post-tasks | Always run tasks that are OS specific"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: always
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags: always
