---
- name: "Git Delta | Get latest version number"
  register: latest_json
  ansible.builtin.uri:
    url: "https://api.github.com/repos/dandavison/delta/releases/latest"
    method: GET
    return_content: true
    status_code: 200
    body_format: json

- name: "Git Delta | Set facts"
  ansible.builtin.set_fact:
    git_delta_latest_version: "{{ latest_json.json.tag_name }}"

- name: "Git Delta | Install bash completion file"
  block:
    - name: "Git Delta | Ensure config directory exists"
      ansible.builtin.file:
        path: "/usr/local/share/bash-completion/completions"
        state: directory
        mode: "0755"

    - name: "Git Delta | Install completion file"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/dandavison/delta/refs/tags/\
          {{ git_delta_latest_version }}/etc/completion/completion.bash"
        dest: "/usr/local/share/bash-completion/completions/delta"
        mode: "0644"

- name: "Git Delta | Install zsh completion file"
  block:
    - name: "Git Delta | Ensure config directory exists"
      ansible.builtin.file:
        path: "/usr/local/share/zsh/site-functions"
        state: directory
        mode: "0755"

    - name: "Git Delta | Install completion file"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/dandavison/delta/refs/tags/\
          {{ git_delta_latest_version }}/etc/completion/completion.zsh"
        dest: "/usr/local/share/zsh/site-functions/_delta"
        mode: "0644"
