---
- name: "LSP servers | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: lsp_servers

- name: "LSP servers | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ lsp_servers_package }}"
    state: present
  tags: lsp_servers

- name: "LSP servers | Install from Node Package Manager"
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  loop: "{{ lsp_servers_npm }}"
  tags: lsp_servers

- name: "LSP Servers | Add rust-analyzer to list of Rustup component"
  when: ansible_system == 'Linux'
  ansible.builtin.command:
    cmd: rustup component add rust-analyzer
  environment:
    RUSTUP_HOME: "{{ ansible_user_dir }}/.rustup"
    CARGO_HOME: "{{ ansible_user_dir }}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.cargo/bin"
  changed_when: false
  tags: lsp_servers
