---
- name: "Bottom | Remove downloaded archives"
  ansible.builtin.file:
    path: "/tmp/{{ item }}.tar.gz"
    state: absent
  loop:
    - completion
    - manpage

- name: "Bottom | Install assets"
  ansible.builtin.include_tasks: assets.yml
