---
- name: "Git Delta | Install package [Debian]"
  when: ansible_os_family == 'Debian'
  become: true
  community.general.cargo:
    name: git-delta
    state: latest
    locked: true
    path: "/usr/local"
  environment:
    RUSTUP_HOME: "{{ ansible_user_dir }}/.rustup"
    CARGO_HOME: "{{ ansible_user_dir }}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.cargo/bin"
  tags:
    - git
    - git-delta
  notify: "Git Delta | Install completion files"

- name: "Git Delta | Install package [Rolling Release]"
  become: true
  ansible.builtin.package:
    name:
      - git-delta
    state: present
  when: ansible_os_family != "Debian"
  tags:
    - git
    - git-delta
