---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Apply opencode role
      ansible.builtin.import_role:
        name: /home/henrib/Programming/deployment-ansible/roles/opencode  # noqa: role-name[path]
