---
- name: "Nerdfonts | Build font information caches"
  become: true
  ansible.builtin.command: fc-cache --force --verbose
  register: nerdfonts_res
  changed_when: "'fc-cache: succeeded' in nerdfonts_res.stdout"
