---
# tasks file for shell
- name: Install shell utilities
  become: true
  ansible.builtin.package:
    name:
      - zsh
      - tmux
      - fzf
      - envsubst
    state: present

- name: Install fastfetch [package manager]
  become: true
  ansible.builtin.package:
    name:
      - fastfetch
    state: present
  when: ansible_os_family != "Ubuntu"

- name: Install fastfetch [Deb file]
  become: true
  ansible.builtin.apt:
    deb: "https://github.com/fastfetch-cli/fastfetch/releases/download/2.26.1/fastfetch-linux-amd64.deb"
  when: ansible_os_family == "Ubuntu"
