---
- name: "Dotfiles | Installation"
  hosts: localhost
  pre_tasks:
    - name: "Dotfiles | Prepare installation"
      ansible.builtin.include_tasks:
        file: pre_tasks/main.yml
        apply:
          tags: always
      tags: always
  post_tasks:
    - name: "Dotfiles | Finalize installation"
      ansible.builtin.include_tasks:
        file: post_tasks/main.yml
        apply:
          tags: always
      tags: always
  roles:
    - role: "netrc"
    - role: "ssh"
    - role: "pipx"
    - role: "rustup"
    - role: "mimeapps"
    - role: "cargo_cache"
    - role: "alacritty"
    - role: "zsh"
    - role: "oh_my_posh"
    - role: "fastfetch"
    - role: "tmux"
    - role: "fzf"
    - role: "nerdfonts"
    - role: "web_browsers"
    - role: "thunderbird"
    - role: "wallpapers"
    - role: "icons"
    - role: "user"
    - role: "network"
    - role: "minicom"
    - role: "wireshark"
    - role: "eza"
    - role: "bat"
    - role: "yazi"
    - role: "bottom"
    - role: "keymapp"
    - role: "nextcloud"
    - role: "owncloud_client"
      when: ansible_facts["hostname"] == "hbuyse-latitude5400"
    - role: "spotify_player"
    - role: "webapplications"
    - role: "discord"
    - role: "zoom"
      when: ansible_facts["hostname"] == "hbuyse-latitude5400"
    - role: "bitwarden"
    - role: "qemu_kvm"
