---
- name: "Dotfiles | Installation"
  hosts: localhost
  pre_tasks:
    - name: "Dotfiles | Prepare installation"
      ansible.builtin.include_tasks: pre_tasks/main.yml
  post_tasks:
    - name: "Dotfiles | Finalize installation"
      ansible.builtin.include_tasks: post_tasks/main.yml
  roles:
    - role: "git"
    - role: "alacritty"
    - role: "git_delta"
    - role: "nodejs"
    - role: "nerdfonts"
      vars:
        nerdfonts_font_dir_prefix: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
    - role: "nvim"
    - role: "direnv"
    - role: "fastfetch"
    - role: "tmux"
      tags:
        - tmux
    - role: "fzf"
    - role: "clang"
    - role: "lsp_servers"
    - role: "vscode"
    - role: "zsh"
    - role: "docker"
    - role: "oh_my_posh"
    - role: "web_browsers"
    - role: "wallpapers"
      vars:
        wallpapers_install_prefix: "{{ lookup('env', 'HOME') }}/.local"
    - role: "discord"
