---
- hosts: localhost
  pre_tasks:
    - import_tasks: pre_tasks/main.yml

  roles:
    - name: git
    - name: alacritty
    - name: nodejs
    - name: nerdfonts
      vars:
        nerdfonts_font_dir_prefix: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
    - name: nvim
    - name: direnv
    - name: fastfetch
    - name: tmux
    - name: fzf
    - name: clang
    - name: lsp_servers
    - name: vscode
