---
- name: "Dotfiles | Installation"
  hosts: localhost
  pre_tasks:
    - name: "Dotfiles | Prepare installation"
      ansible.builtin.include_tasks:
        file: pre_tasks/main.yml
        apply:
          tags: always
      tags: always
  post_tasks:
    - name: "Dotfiles | Finalize installation"
      ansible.builtin.include_tasks:
        file: post_tasks/main.yml
        apply:
          tags: always
      tags: always
  roles:
    - role: "netrc"
    - role: "ssh"
    - role: "mimeapps"
    - role: "git"
    - role: "alacritty"
    - role: "git_delta"
    - role: "nodejs"
    - role: "nerdfonts"
    - role: "nvim"
    - role: "direnv"
    - role: "fastfetch"
    - role: "tmux"
    - role: "fzf"
    - role: "clang"
    # LSP Servers
    - role: "ansiblels"
    - role: "bashls"
    - role: "composels"
    - role: "cssls"
    - role: "htmlls"
    - role: "jsonls"
    - role: "luals"
    - role: "markdownls"
    - role: "pyright"
    - role: "ruff"
    - role: "rust_analyzer"
    - role: "texlab"
    - role: "yamlls"
    # End LSP Servers
    - role: "vscode"
    - role: "zsh"
    - role: "docker"
    - role: "podman"
    - role: "oh_my_posh"
    - role: "web_browsers"
    - role: "wallpapers"
    - role: "discord"
    - role: "icons"
    - role: "xfce4"
    - role: "user"
    - role: "eza"
    - role: "pre_commit"
    - role: "ripgrep"
    - role: "bat"
    - role: "bottom"
    - role: "python"
    - role: "zellij"
    - role: "keymapp"
    - role: "nextcloud"
    - role: "spotify"
    - role: "qemu_kvm"
    # Formatters
    - role: "black"
    - role: "codespell"
    - role: "isort"
    - role: "perltidy"
    - role: "prettier"
    - role: "shfmt"
    - role: "stylua"
    - role: "yamlfmt"
    - role: "network"
