---
collections:
  - name: ansible.posix
  - name: community.general
    version: ">=13.1.0,<14.0.0"
  - name: kewlfft.aur
roles:
  - src: https://github.com/roots/ansible-output-prettify.git
    name: ansible-output-prettify
