---
- name: "Sway | Installation"
  hosts: localhost
  pre_tasks:
    - name: "Sway | Prepare installation"
      ansible.builtin.include_tasks:
        file: pre_tasks/main.yml
        apply:
          tags: always
      tags: always
  post_tasks:
    - name: "Sway | Finalize installation"
      ansible.builtin.include_tasks:
        file: post_tasks/main.yml
        apply:
          tags: always
      tags: always
  roles:
    # - role: "lightdm"
    #   vars:
    #     lightdm_active_monitor: "DP-3"
    - role: "greetd"
      when:
        - ansible_hostname != "hbuyse-latitude5400"
        - ansible_system != "FreeBSD"
    - role: "tuigreet"
      when:
        - ansible_hostname != "hbuyse-latitude5400"
        - ansible_system != "FreeBSD"
    - role: "lightdm"
      when: ansible_system == "FreeBSD"
    - role: "alacritty"
    - role: "zsh"
    - role: "oh_my_posh"
    - role: "fastfetch"
    - role: "tmux"
    - role: "fzf"
    - role: "nerdfonts"
    - role: "wallpapers"
    - role: "brightnessctl"
      when: ansible_system != "FreeBSD"
    - role: "wayland_sessions"
    - role: "swaylock"
    - role: "swayidle"
    - role: "sway"
    - role: "waybar"
    - role: "kanshi"
    - role: "mako"
      when: ansible_os_family in ["Debian"]
    - role: "swaync"
      when: ansible_os_family not in ["Debian"]
    - role: "wofi"
    - role: "fuzzel"
      when: ansible_os_family not in ["Debian"]
    - role: "xdg_desktop_portal"
    - role: "wireplumber"
    - role: "tuned"
    - role: "wlprop"
    - role: "wlsunset"
