---
- name: "Sway Window Manager | Installation"
  hosts: localhost
  pre_tasks:
    - name: "Sway | Prepare installation"
      ansible.builtin.include_tasks:
        file: pre_tasks/main.yml
        apply:
          tags: always
      tags: always
  post_tasks:
    - name: "Sway | Finalize installation"
      ansible.builtin.include_tasks:
        file: post_tasks/main.yml
        apply:
          tags: always
      tags: always
  roles:
    # Terminals
    - role: "foot"
    - role: "alacritty"
    - role: "themes"

    # Sway
    - role: "sway"
    - role: "wayland_sessions"
    # Nvidia support if needed
    - role: "nvidia"
      when: nvidia_detection.rc == 0
    - role: "wallpapers"
    - role: "icons"
    # Tools for sway
    - role: "swaylock"
    - role: "swayidle"
    - role: "brightnessctl"
    # Wayland tools
    - role: "waybar"
    - role: "kanshi"
    - role: "swaync"
    - role: "wofi"
      when: ansible_facts.os_family in ["Debian"]
    - role: "fuzzel"
      when: ansible_facts.os_family not in ["Debian"]
    - role: "wlprop"
    - role: "wlsunset"
    # Portal to select which screen to cast
    - role: "xdg_desktop_portal"
    - role: "wireplumber"
    - role: "tuned"
