---
- name: "Sway | Installation"
  hosts: localhost
  pre_tasks:
    - name: "Sway | Prepare installation"
      ansible.builtin.include_tasks:
        file: pre_tasks/main.yml
        apply:
          tags: always
      tags: always
  post_tasks:
    - name: "Sway | Finalize installation"
      ansible.builtin.include_tasks:
        file: post_tasks/main.yml
        apply:
          tags: always
      tags: always
  roles:
    # - role: "lightdm"
    #   vars:
    #     lightdm_active_monitor: "DP-3"
    - role: "wallpapers"
    - role: "brightnessctl"
    - role: "wayland_sessions"
    - role: "swaylock"
    - role: "swayidle"
    - role: "sway"
    - role: "waybar"
    - role: "kanshi"
    - role: "mako"
    - role: "wofi"
    - role: "wireplumber"
