---
- name: "GUI tools | Installation"
  hosts: localhost
  pre_tasks:
    - name: "GUI tools | Prepare installation"
      ansible.builtin.include_tasks:
        file: pre_tasks/main.yml
        apply:
          tags: always
      tags: always
  post_tasks:
    - name: "GUI tools | Finalize installation"
      ansible.builtin.include_tasks:
        file: post_tasks/main.yml
        apply:
          tags: always
      tags: always
  roles:
    # Configuration
    - role: "netrc"
    - role: "ssh"
    - role: "user"
    - role: "network"
    - role: "mimeapps"
    # Tools
    - role: "web_browsers"
    - role: "thunderbird"
    - role: "minicom"
    - role: "wireshark"
    - role: "qemu_kvm"
    - role: "keymapp"
    - role: "bitwarden"
    - role: "zoom"
      when: ansible_facts.hostname == "hbuyse-promax14"
    # Desktop client for cloud
    - role: "nextcloud"
    - role: "owncloud_client"
      when: ansible_facts.hostname == "hbuyse-promax14"
    # Web applications
    - role: "webapplications"
    # CPU management
    - role: "tuned"
