---
themes_gtk_dir: "{{ ansible_user_dir }}/.local/share/themes"

themes_gtk3_config_dir: "{{ ansible_user_dir }}/.config/gtk-3.0"
themes_gtk4_config_dir: "{{ ansible_user_dir }}/.config/gtk-4.0"

themes_matcha_enable: true
themes_matcha_github_user: "vinceliuice"
themes_matcha_github_repo: "Matcha-gtk-theme"

themes_catppuccin_enable: true
themes_catppuccin_github_user: "Fausto-Korpsvart"
themes_catppuccin_github_repo: "Catppuccin-GTK-Theme"
