---
themes_dir: "{{ ansible_user_dir }}/.config/themes"
themes_list:
  - catppuccin

themes_gtk_dir: "{{ ansible_user_dir }}/.local/share/themes"
themes_matcha_enable: true
themes_matcha_github_user: "vinceliuice"
themes_matcha_github_repo: "Matcha-gtk-theme"

themes_catppuccin_enable: true
themes_catppuccin_github_user: "Fausto-Korpsvart"
themes_catppuccin_github_repo: "Catppuccin-GTK-Theme"
