---
- name: "Pipx | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: pipx

- name: "Pipx | Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ pipx_packages }}"
    state: "present"
  when: pipx_packages is defined
  tags: pipx

- name: "Pipx | Install from PIP"
  ansible.builtin.pip:
    name: "pipx"
    state: "latest"
    extra_args: "--user"
  when: pipx_packages is not defined
  tags: pipx
