---
- name: "Prettier | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags:
    - prettier
    - formatter

- name: "Prettier | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ prettier_packages }}"
    state: present
  tags:
    - prettier
    - formatter
  when: prettier_packages is defined

- name: "Prettier | Install from Node Package Manager"
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: latest
    production: true
    no_optional: true
  tags:
    - prettier
    - formatter
  loop: "{{ prettier_npm_packages }}"
  when: (prettier_packages is not defined) or prettier_force_source_install
