---
- name: "Prettier | Install from Node Package Manager"
  become: true
  community.general.npm:
    name: "prettier"
    global: true
    state: latest
    path: "/usr/local"
    production: true
    no_optional: true
