---
- name: "Spotify Player | Check that client id and secret are populated"
  ansible.builtin.assert:
    that:
      - spotify_player_client_id is defined
      - spotify_player_client_id | length > 0
      - spotify_player_client_secret is defined
      - spotify_player_client_secret | length > 0
    fail_msg: "spotify_player_client_id and spotify_player_client_secret must not be empty (check your host_vars/localhost.yml)"
    quiet: true
  tags: spotify_player

- name: "Spotify Player | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags:
    - spotify_player

- name: "Spotify Player | Install Rust package with locked dependencies"
  tags: spotify_player
  when: spotify_player_packages is not defined
  block:
    - name: "Spotify Player | Install dependencies"
      become: true
      ansible.builtin.package:
        name: "{{ spotify_player_dependencies }}"

    - name: "Spotify Player | Install Rust package with locked dependencies"
      community.general.cargo:
        name: "spotify_player"
        state: "latest"
        locked: true
        features: "{{ spotify_player_features }}"
      notify:
        - "Spotify Player | Install zsh completion file"
        - "Spotify Player | Install bash completion file"

- name: "Spotify Player | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ spotify_player_packages }}"
    state: "latest"
  when: spotify_player_packages is defined
  tags: spotify_player
  notify:
    - "Spotify Player | Install zsh completion file"
    - "Spotify Player | Install bash completion file"

- name: "Spotify Player | Copy configuration files"
  tags: spotify_player
  block:
    - name: "Spotify Player | Ensure configuration directory exists"
      ansible.builtin.file:
        path: "{{ spotify_player_config_dir }}"
        state: "directory"
        mode: "0755"

    - name: "Spotify Player | Copy configuration file"
      ansible.builtin.template:
        src: "app.toml.j2"
        dest: "{{ spotify_player_config_dir }}/app.toml"
        mode: "0644"

    - name: "Spotify Player | Download theme file"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/aome510/spotify-player/refs/heads/master/examples/theme.toml"
        dest: "{{ spotify_player_config_dir }}/theme.toml"
        mode: "0644"
