---
- name: "Wallpapers | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: wallpapers

- name: "Wallpapers | Install dependencies"
  become: true
  ansible.builtin.package:
    name: "{{ wallpapers_dependencies }}"
    state: present
  tags: wallpapers

- name: "Wallpapers | Ensure wallpaper directory exists"
  become: "{{ (wallpapers_user == 'root') | bool }}"
  ansible.builtin.file:
    path: "{{ wallpapers_install_dir }}"
    state: directory
    mode: "0755"
    recurse: true
  tags: wallpapers

- name: "Wallpapers | Install SVG files"
  become: "{{ (wallpapers_user == 'root') | bool }}"
  tags: wallpapers
  block:
    - name: "Wallpapers | Generate SVG file with colors"
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -o pipefail
          cat {{ role_path }}/files/coding.svg | envsubst > {{ wallpapers_install_dir }}/coding.svg
        creates: "{{ wallpapers_install_dir }}/coding.svg"
      environment:
        OUTLINE: "#f2cdcd"
        INSIDE: "#dd7878"
        BACKGROUND: "#1e1e2e"

    - name: "Wallpapers | Create SVG links"
      ansible.builtin.file:
        src: "{{ wallpapers_install_dir }}/coding.svg"
        dest: "{{ wallpapers_install_dir }}/{{ item }}.svg"
        owner: "{{ wallpapers_user }}"
        group: "{{ wallpapers_user }}"
        state: "link"
      loop:
        - "wallpaper"
        - "locker"

- name: "Wallpapers | Install PNG files"
  become: "{{ (wallpapers_user == 'root') | bool }}"
  tags: wallpapers
  block:
    - name: "Wallpapers | Convert SVG to PNG files"
      ansible.builtin.command:
        cmd: convert {{ wallpapers_install_dir }}/coding.svg {{ wallpapers_install_dir }}/coding.png
        creates: "{{ wallpapers_install_dir }}/coding.png"

    - name: "Wallpapers | Create PNG links"
      ansible.builtin.file:
        src: "{{ wallpapers_install_dir }}/coding.png"
        dest: "{{ wallpapers_install_dir }}/{{ item }}.png"
        owner: "{{ wallpapers_user }}"
        group: "{{ wallpapers_user }}"
        state: "link"
      loop:
        - "wallpaper"
        - "locker"
