---
- name: "Keymapp | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: keymapp

- name: "Keymapp | Install dependencies"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ keymapp_dependencies }}"
  when: keymapp_dependencies is defined
  tags: keymapp

- name: "Keymapp | Download latest archive"
  ansible.builtin.get_url:
    url: "https://oryx.nyc3.cdn.digitaloceanspaces.com/keymapp/keymapp-latest.tar.gz"
    dest: "/tmp/"
    mode: "0644"
  notify: "Keymapp | Remove downloaded archive"
  tags: keymapp

- name: "Keymapp | Ensure directory exist"
  become: "{{ keymapp_become }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ keymapp_bin_dir }}"
    - "{{ keymapp_icons_dir }}"
  tags: keymapp

- name: "Keymapp | Extract archive files"
  become: "{{ keymapp_become }}"
  ansible.builtin.unarchive:
    src: "/tmp/keymapp-latest.tar.gz"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    include:
      - "{{ item.file }}"
  loop:
    - file: keymapp
      dest: "{{ keymapp_bin_dir }}"
      mode: "0755"
    - file: icon.png
      dest: "{{ keymapp_icons_dir }}"
      mode: "0644"
  tags: keymapp

- name: "Keymapp | Rename icon file"
  become: "{{ keymapp_become }}"
  tags: keymapp
  block:
    - name: "Keymapp | Copy icon file"
      ansible.builtin.copy:
        src: "{{ keymapp_icons_dir }}/icon.png"
        dest: "{{ keymapp_icons_dir }}/keymapp.png"
        mode: "0644"

    - name: "Keymapp | Remove old icon file"
      ansible.builtin.file:
        path: "{{ keymapp_icons_dir }}/icon.png"
        state: absent

- name: "Keymapp | Copy desktop file"
  become: "{{ keymapp_become }}"
  ansible.builtin.copy:
    src: "keymapp.desktop"
    dest: "{{ keymapp_desktop_dir }}"
    mode: "0644"
  tags: keymapp

- name: "Keymapp | Copy udev rule files"
  become: true
  ansible.builtin.template:
    src: "50-zsa.rules.j2"
    dest: "/etc/udev/rules.d/50-zsa.rules"
    mode: "0644"
  tags: keymapp

- name: "Keymapp | Add current user to 'plugdev' group"
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "plugdev"
    append: true
  tags: keymapp
