---
- name: "GDM | Include OS specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"
  tags: gdm

- name: "GDM | Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ gdm_packages }}"
    state: "present"
  tags: gdm
