---
- name: "Minicom | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: [minicom, serial]

- name: "Minicom | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ minicom_packages }}"
    update_cache: true
    state: present
  tags: [minicom, serial]
  when: minicom_packages is defined

- name: "Minicom | Add '{{ minicom_group }}' group to user" # noqa: name[template]
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "{{ minicom_group }}"
    append: true
  tags: [minicom, serial]

- name: "Minicom | Copy default file"
  ansible.builtin.template:
    src: "minirc.dfl.j2"
    dest: "{{ minicom_dfl_file_location }}"
    mode: "0644"
  tags: [minicom, serial]
