---
- name: "LazyGit | Get latest version number"
  register: lazygit_latest_json
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ lazygit_github_user }}/{{ lazygit_github_repo }}/releases/latest"
    method: GET
    return_content: true
    status_code: 200
    body_format: json
  tags:
    - lazygit
    - git

- name: "LazyGit | Set facts"
  ansible.builtin.set_fact:
    lazygit_latest_version: "{{ lazygit_latest_json.json.tag_name[1:] }}"
  tags:
    - lazygit
    - git

- name: "LazyGit | Install executable"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/{{ lazygit_github_user }}/{{ lazygit_github_repo }}/releases/download/v{{ lazygit_latest_version
      }}/lazygit_{{ lazygit_latest_version }}_{{ ansible_system }}_{{ ansible_architecture }}.tar.gz"
    dest: "{{ ansible_user_dir }}/.local/bin"
    mode: "0755"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    include:
      - "lazygit"
    remote_src: true
  tags:
    - lazygit
    - git

- name: "LazyGit | Install configuration"
  tags:
    - lazygit
    - git
  block:
    - name: "LazyGit | Ensure configuration directory exists"
      ansible.builtin.file:
        path: "{{ lazygit_config_dir }}"
        state: directory
        mode: "0755"

    - name: "LazyGit | Copy configuration"
      ansible.builtin.copy:
        src: "config.yml"
        dest: "{{ lazygit_config_dir }}"
        mode: "0644"
