---
- name: "Check that latitude and longitude is populated"
  ansible.builtin.assert:
    that:
      - wlsunset_config is defined
      - wlsunset_config is mapping
      - wlsunset_config.latitude is defined
      - wlsunset_config.latitude is float
      - wlsunset_config.longitude is defined
      - wlsunset_config.longitude is float
    fail_msg: "wlsunset_config must not be empty (check your host_vars/localhost.yml)"
    quiet: true
  tags: wlsunset

- name: "Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags: wlsunset

- name: "Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ wlsunset_packages }}"
    state: present
  when: wlsunset_packages is defined
  tags: wlsunset

- name: "Copy service file"
  ansible.builtin.template:
    src: "wlsunset.service.j2"
    dest: "{{ wlsunset_systemd_dir }}/wlsunset.service"
    mode: "0644"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_gid }}"
  notify: "Restart wlsunset service"
  tags: wlsunset
