---
- name: "Eza | Get latest version number"
  register: latest_json
  ansible.builtin.uri:
    url: "https://api.github.com/repos/eza-community/eza/releases/latest"
    method: GET
    return_content: true
    status_code: 200
    body_format: json

- name: "Eza | Set facts"
  ansible.builtin.set_fact:
    eza_latest_version: "{{ latest_json.json.tag_name[1:] }}"

- name: "Eza | Download eza extra archives"
  ansible.builtin.get_url:
    url: "https://github.com/eza-community/eza/releases/download/v{{ eza_latest_version }}/{{ item }}-{{ eza_latest_version }}.tar.gz"
    dest: "/tmp/"
    mode: "0644"
  loop:
    - completions
    - man
  notify: "Eza | Remove downloaded archives"

- name: "Eza | Install completion shell files"
  ansible.builtin.include_tasks:
    file: completions.yml
  loop:
    - completion_file: _eza
      shell: zsh
      install_dir: "/usr/local/share/zsh/site-functions"
    - completion_file: eza
      shell: bash
      install_dir: "/usr/local/share/bash-completion/completions"

- name: "Eza | Install manpage files"
  ansible.builtin.include_tasks:
    file: manpages.yml
  loop:
    - number: 1
      name: eza
    - number: 5
      name: eza_colors
    - number: 5
      name: eza_colors-explanation
