---
kanshi_work_confs:
  left:
    - vertical: "Dell Inc. DELL P2419HC DQKSJ73"
      horizontal: "Dell Inc. DELL P2419H 87V1Y9BR2V2I"
  right:
    - vertical: "Dell Inc. DELL P2419H 3G03P33"
      horizontal: "Dell Inc. DELL P2419HC 69JSJ73"
    - vertical: "Dell Inc. DELL P2419H BGL8Q33"
      horizontal: "Dell Inc. DELL P2419H 83Z2P33"
    - vertical: "Dell Inc. DELL P2419H 6QD7K43"
      horizontal: "Dell Inc. DELL P2419H 3K8KBR2"
