---
- name: "Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
  tags: kanshi

- name: "Install required packages"
  become: true
  ansible.builtin.package:
    name: "{{ kanshi_packages }}"
  tags: kanshi

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: "{{ (ansible_facts.os_family == 'RedHat') | ansible.builtin.ternary('dnf5', 'auto') }}"
    strategy: first
  tags: kanshi

- name: "Store version as fact"
  ansible.builtin.set_fact:
    kanshi_version: "{{ ansible_facts.packages['kanshi'][0]['version'] | regex_search('[0-9]+.[0-9]+.[0-9]+') }}"
  tags: kanshi

- name: "Install static configuration files"
  tags: kanshi
  block:
    - name: "Ensure directory exist"
      ansible.builtin.file:
        path: "{{ kanshi_config_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ kanshi_config_owner }}"
        group: "{{ kanshi_config_group }}"

    - name: "Copy root configuration"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ kanshi_config_dir }}"
        mode: "{{ item.mode }}"
        owner: "{{ kanshi_config_owner }}"
        group: "{{ kanshi_config_group }}"
      notify: "Enable and restart kanshi service"
      loop:
        - src: "config"
          mode: "0644"
        - src: "notify.sh"
          mode: "0755"

- name: "Install dynamic configuration files"
  tags: kanshi
  block:
    - name: "Ensure directory exist"
      ansible.builtin.file:
        path: "{{ kanshi_configd_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ kanshi_config_owner }}"
        group: "{{ kanshi_config_group }}"

    - name: "Generate basic configuration"
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ kanshi_configd_dir }}/{{ item | replace('.j2', '') }}"
        mode: "0644"
        owner: "{{ kanshi_config_owner }}"
        group: "{{ kanshi_config_group }}"
      notify: "Enable and restart kanshi service"
      loop:
        - "home.j2"
        - "one-screen.j2"

    - name: "Generate work configuration"
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ kanshi_configd_dir }}/{{ item | replace('.j2', '') }}"
        mode: "0644"
        owner: "{{ kanshi_config_owner }}"
        group: "{{ kanshi_config_group }}"
      notify: "Enable and restart kanshi service"
      loop:
        - "work-com.j2"
        - "work.j2"
      when:
        - kanshi_work_confs is defined

- name: "Install service file"
  become: true
  tags: kanshi
  block:
    - name: "Ensure directory exist"
      ansible.builtin.file:
        path: "{{ kanshi_systemd_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ kanshi_config_owner }}"
        group: "{{ kanshi_config_group }}"

    - name: "Copy service file"
      ansible.builtin.copy:
        src: "kanshi.service"
        dest: "{{ kanshi_systemd_dir }}"
        mode: "0644"
        owner: "{{ kanshi_config_owner }}"
        group: "{{ kanshi_config_group }}"
      tags: kanshi
      notify: "Enable and restart kanshi service"
