---
- name: "VSCode | Install dependencies [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - wget
      - gpg
      - apt-transport-https

- name: "VSCode | Add deb repository - modern"
  when: ansible_version.full >= "2.15.0"
  ansible.builtin.include_tasks:
    file: debian-modern.yml
    apply:
      tags: vscode

- name: "VSCode | Add deb repository - legacy"
  when: ansible_version.full < "2.15.0"
  ansible.builtin.include_tasks:
    file: debian-legacy.yml
    apply:
      tags: vscode
