---
- name: "VSCode | Install dependencies [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - wget
      - gpg
      - apt-transport-https

- name: "VSCode | Install repository [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.deb822_repository:
    name: vscode
    types: deb
    uris: "https://packages.microsoft.com/repos/code"
    suites: "stable"
    components:
      - main
    architectures:
      - "{{ deb_arch }}"
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
