---
- name: "VSCode | Download GPG key"
  become: true
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    dest: "/etc/apt/keyrings/vscode.asc"
    mode: "0644"

- name: "VSCode | Add deb repository"
  become: true
  ansible.builtin.apt_repository:
    filename: vscode
    repo: "deb [arch={{ deb_arch }} signed-by=/etc/apt/keyrings/vscode.asc] https://packages.microsoft.com/repos/code stable main"
    state: present
    update_cache: false
