---
- name: "VSCode | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: vscode

- name: "VSCode | Add dependencies and repo"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: vscode
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: vscode

- name: "VSCode | Install VS Code"
  become: true
  ansible.builtin.package:
    update_cache: true
    state: present
    name:
      - code
  tags:
    - vscode
