---
- name: "VSCode | Install [Debian]"
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - vscode

- name: "VSCode | Install [Archlinux]"
  ansible.builtin.import_tasks: archlinux.yml
  when: ansible_os_family == 'Archlinux'
  tags:
    - vscode

- name: "VSCode | Install [Suse]"
  ansible.builtin.import_tasks: archlinux.yml
  when: ansible_os_family == 'Archlinux'
  tags:
    - vscode
