---
- name: "VSCode | Install [Debian]"
  ansible.builtin.include_tasks:
    file: debian.yml
    apply:
      tags: vscode
  when: ansible_os_family == 'Debian'
  tags: vscode

- name: "VSCode | Install [Archlinux]"
  ansible.builtin.include_tasks:
    file: archlinux.yml
    apply:
      tags: vscode
  when: ansible_os_family == 'Archlinux'
  tags: vscode

- name: "VSCode | Install [Suse]"
  ansible.builtin.include_tasks:
    file: suse.yml
    apply:
      tags: vscode
  when: ansible_os_family == 'Suse'
  tags:
    - vscode
