---
- name: "VSCode | Add yum repository"
  become: true
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code repository
    file: vscode
    baseurl: "https://packages.microsoft.com/yumrepos/vscode"
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
    gpgcheck: true
    enabled: true
