---
- name: "VSCode | Install key [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: "https://packages.microsoft.com/keys/microsoft.asc"

- name: "VSCode | Add repository configuration [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.copy:
    src: "vscode.repo"
    dest: "/etc/zypp/repos.d/vscode.repo"
    mode: "0600"
    owner: root
    group: root

- name: "VSCode | Install package [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.package:
    name:
      - code
    state: present
    update_cache: true
