---
- name: "Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags:
    - opencode
    - ai

- name: "Install program from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ opencode_packages }}"
    state: present
  when: opencode_packages is defined
  tags:
    - opencode
    - ai

- name: "Install from Node Package Manager"
  when: opencode_packages is not defined
  community.general.npm:
    name: "{{ opencode_npm_package }}"
    global: true
    state: latest
    production: true
    no_optional: true
  tags:
    - opencode
    - ai

- name: "Copy configuration"
  tags:
    - opencode
    - ai
  block:
    - name: "Ensure configuration directory exists"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        mode: "0755"
      loop:
        - "{{ opencode_config_dir }}"
        - "{{ opencode_agents_dir }}"

    - name: "Copy static configuration files"
      ansible.builtin.copy:
        src: "cli.json"
        dest: "{{ opencode_config_dir }}"
        mode: "0644"

    - name: "Copy Opencode configuration file"
      ansible.builtin.template:
        src: "opencode.jsonc.j2"
        dest: "{{ opencode_config_dir }}/opencode.jsonc"
        mode: "0644"

    - name: "Copy Opencode agent files"
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ opencode_agents_dir }}/{{ item | basename }}"
        mode: "0644"
      loop:
        - agents/review.md
        - agents/testu.md
      when: opencode_code_review_model is defined

    - name: "Remove old configuration files"
      ansible.builtin.file:
        path: "{{ opencode_config_dir }}/{{ item }}"
        state: "absent"
      loop:
        - tui.jsonc
