set $opacity 0.95
for_window [class=".*"] opacity set $opacity
for_window [app_id=".*"] opacity set $opacity

# Automatically move some applications to dedicated workspaces
for_window [app_id="firefox"] move window to workspace $wsWeb
for_window [class="(?i)chromium"] move window to workspace $wsWeb
for_window [class="(?i)chromium" instance="youtube.com"] move window to workspace $ws7
for_window [instance="google-chrome"] move window to workspace $wsWeb
for_window [app_id="thunderbird"] move window to workspace $wsMail
for_window [app_id="(?i)evolution"] move container to workspace $wsMail
for_window [app_id="(?i)outlook"] move container to workspace $wsMail
for_window [class="(?i)mattermost"] move container to workspace $wsMessaging
for_window [app_id="(?i)mattermost"] move container to workspace $wsMessaging
for_window [instance="bitwarden"] move window to workspace $wsPasswords
for_window [instance="keepass.*"] move window to workspace $wsPasswords
for_window [app_id="(?i).*keepass.*"] move container to workspace $wsPasswords
for_window [instance="spotify"] move window to workspace $wsSpotify
for_window [instance="discord"] move container to workspace $wsMessaging
for_window [instance="zoom"] move container to workspace $wsZoom

# WebApps
for_window [app_id="chrome-discord.com.*"] move window to workspace $wsMessaging
for_window [app_id="chrome-mattermost.*"] move window to workspace $wsMessaging
for_window [app_id="chrome-open.spotify.com.*"] move window to workspace $wsSpotify
for_window [app_id="chrome-youtube.com.*"] move window to workspace $wsSpotify

# Activate the inhibitor while zoom metting is running:
# - 'fullscreen' will inhibit idle when the view is fullscreen (or a descendant of a fullscreen container) and is visible
# - 'focus' will inhibit idle when the window is focused by any seat.
# - 'open' will inhibit idle until the window is closed (or the inhibitor is unset/changed).
# - 'visible' will inhibit idle when the window is visible on any output.
# - 'none' will remove any existing idle inhibitor for the window.
for_window [instance="zoom" title="Meeting"] inhibit_idle fullscreen

# Some Zoom windows are floating
for_window [instance="zoom" title="Meeting chat"]   floating enable
for_window [instance="zoom" title="Participants.*"] floating enable
for_window [instance="zoom" title="Zoom Workplace"] floating enable

# Email client reminders are floating
for_window [app_id="thunderbird" title=".*Reminder"] floating enable
for_window [app_id="evolution-alarm-notify"]         floating enable

# Don't allow applications to inhibit shortcuts, i.e. grab total control of the
# keyboard. Chrome currently abuses this by enabling it for all "--app=..."
# shortcuts.
seat * shortcuts_inhibitor disable
#  vim: set ts=4 sw=4 tw=0 et ft=swayconfig :
