---
- name: "ShFmt | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: [shfmt, formatter, formatters]

- name: "ShFmt | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ shfmt_packages }}"
    update_cache: true
    state: present
  tags: [shfmt, formatter, formatters]
  when: shfmt_packages is defined

- name: "ShFmt | Install from source"
  ansible.builtin.include_tasks:
    file: "source.yml"
    apply:
      tags: [shfmt, formatter, formatters]
  tags: [shfmt, formatter, formatters]
  when: (shfmt_packages is not defined) or shfmt_force_source_install
