---
- name: "ShFmt | Get latest version number"
  register: latest_json
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ shfmt_github_user }}/{{ shfmt_github_repo }}/releases/latest"
    method: GET
    return_content: true
    status_code: 200
    body_format: json

- name: "ShFmt | Set facts"
  ansible.builtin.set_fact:
    shfmt_latest_version: "{{ latest_json.json.tag_name }}"

- name: "ShFmt | Install executable"
  become: true
  ansible.builtin.get_url:
    url:
      "https://github.com/{{ shfmt_github_user }}/{{ shfmt_github_repo }}/releases/download/{{ shfmt_latest_version }}/\
      shfmt_{{ shfmt_latest_version }}_{{ ansible_system | lower }}_{{ alt_arch }}"
    dest: "/usr/local/bin/shfmt"
    mode: "0755"
