---
- name: "Web Browsers | Remove firefox installation as snap"
  become: true
  community.general.snap:
    name: firefox
    state: absent
  register: web_browsers_snap_uninstall

- name: "Web Browsers | Reinstall firefox as debian package"  # no-qa: no-handler
  become: true
  when: web_browsers_snap_uninstall.changed  # noqa: no-handler
  block:
    - name: "Web Browsers | Uninstall Firefox debian package"
      ansible.builtin.package:
        name: firefox
        state: absent

    - name: "Web Browsers | Add Mozilla deb repository"
      ansible.builtin.deb822_repository:
        name: mozilla
        enabled: true
        types: deb
        uris: "https://packages.mozilla.org/apt"
        suites: "mozilla"
        components:
          - main
        signed_by: "https://packages.mozilla.org/apt/repo-signing-key.gpg"

    - name: "Web Browsers | Add preferences file for Firefox"
      ansible.builtin.copy:
        src: "firefox.pref"
        dest: "/etc/apt/preferences.d/firefox.pref"
        mode: "0644"

- name: "Web Browsers | Add Vivaldi repo"
  become: true
  ansible.builtin.deb822_repository:
    name: vivaldi
    types:
      - deb
    uris: "https://repo.vivaldi.com/stable/deb/"
    architectures:
      - amd64
    components:
      - main
    suites:
      - stable
    signed_by: https://repo.vivaldi.com/stable/linux_signing_key.pub
    state: present
    enabled: true
