---
- name: "Web Browsers | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags:
    - web
    - browser
    - browsers

- name: "Web Browsers | Include OS specific tasks"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags:
        - web
        - browser
        - browsers
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags:
    - web
    - browser
    - browsers

- name: "Web Browsers | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ web_browsers_packages }}"
    state: present
  tags:
    - web
    - browser
    - browsers
