---
# tasks file for direnv
- import_tasks: source-install.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: package-install.yml
  when: ansible_distribution != "Ubuntu"

- name: "direnv | Create symlink to config"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/direnv"
    state: link
    force: true
