---
# tasks file for direnv
- name: "Direnv | Install from sources"
  ansible.builtin.include_tasks: source-install.yml
  when: ansible_os_family == "Debian"

- name: "Direnv | Install from package manager"
  ansible.builtin.include_tasks: package-install.yml
  when: ansible_os_family != "Debian"

- name: "Direnv | Create symlink to config"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/direnv"
    state: link
    force: true
