---
- name: "Direnv | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: direnv

- name: "Direnv | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ direnv_packages }}"
  when: direnv_packages is defined
  tags: direnv

- name: "Direnv | Install from sources"
  ansible.builtin.include_tasks:
    file: source-install.yml
    apply:
      tags: direnv
  when: direnv_packages is not defined
  tags: direnv

- name: "Direnv | Ensure config directory exists"
  ansible.builtin.file:
    path: "{{ direnv_config_dir }}"
    state: directory
    mode: "0755"
  tags: direnv

- name: "Direnv | Copy direnvrc file"
  ansible.builtin.copy:
    src: "direnvrc"
    dest: "{{ direnv_config_dir }}"
    mode: "0644"
  tags: direnv

- name: "Direnv | Copy direnv.toml template file"
  ansible.builtin.template:
    src: "direnv.toml.j2"
    dest: "{{ direnv_config_dir }}"
    mode: "0644"
  tags: direnv
