---
# tasks file for direnv
- import_tasks: source-install.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: package-install.yml
  when: ansible_distribution != "Ubuntu"

- name: "direnv | Install man pages into {{ direnv_man_install_dir }}"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/direnv/direnv/archive/refs/tags/v{{ direnv_version }}.tar.gz"
    dest: "{{ direnv_man_install_dir }}/man1"
    remote_src: true
    keep_newer: true
    include:
      - "direnv-{{ direnv_version }}/man/direnv.1"
      - "direnv-{{ direnv_version }}/man/direnv.toml.1"
      - "direnv-{{ direnv_version }}/man/direnv-fetchurl.1"
      - "direnv-{{ direnv_version }}/man/direnv-stdlib.1"
    extra_opts:
      - "--strip-components=2"

- name: "direnv | Create symlink to config"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/direnv"
    state: link
    force: true
