---
- name: "direnv | Install binary into {{ direnv_bin_install_dir }}"
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/direnv/direnv/releases/download/v{{ direnv_version }}/direnv.{{ ansible_system | lower }}-{{ alt_arch }}"
    dest: "{{ direnv_bin_install_dir }}/direnv"
    mode: 0755

- name: "direnv | Install man pages into {{ direnv_man_install_dir }}"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/direnv/direnv/archive/refs/tags/v{{ direnv_version }}.tar.gz"
    dest: "{{ direnv_man_install_dir }}/man1"
    remote_src: true
    keep_newer: true
    include:
      - "direnv-{{ direnv_version }}/man/direnv.1"
      - "direnv-{{ direnv_version }}/man/direnv.toml.1"
      - "direnv-{{ direnv_version }}/man/direnv-fetchurl.1"
      - "direnv-{{ direnv_version }}/man/direnv-stdlib.1"
    extra_opts:
      - "--strip-components=2"

- name: "direnv | Ensure {{ direnv_man_install_dir }} directory exists"
  file:
    path: "{{ direnv_man_install_dir }}"
    state: directory
  become: true
