---
clang_packages:
  # LLVM
  - "libllvm{{ clang_llvm_versions | last }}"
  - "llvm-{{ clang_llvm_versions | last }}"
  - "llvm-{{ clang_llvm_versions | last }}-dev"
  - "llvm-{{ clang_llvm_versions | last }}-doc"
  - "llvm-{{ clang_llvm_versions | last }}-examples"
  - "llvm-{{ clang_llvm_versions | last }}-runtime"
  # Clang and co
  - "clang-{{ clang_llvm_versions | last }}"
  - "clang-tools-{{ clang_llvm_versions | last }}"
  - "clang-{{ clang_llvm_versions | last }}-doc"
  - "libclang-common-{{ clang_llvm_versions | last }}-dev"
  - "libclang-{{ clang_llvm_versions | last }}-dev"
  - "libclang1-{{ clang_llvm_versions | last }}"
  - "clang-format-{{ clang_llvm_versions | last }}"
  - "python3-clang-{{ clang_llvm_versions | last }}"
  - "clangd-{{ clang_llvm_versions | last }}"
  - "clang-tidy-{{ clang_llvm_versions | last }}"
  # compiler-rt
  - "libclang-rt-{{ clang_llvm_versions | last }}-dev"
  # lldb
  - "lldb-{{ clang_llvm_versions | last }}"
  # lld (linker)
  - "lld-{{ clang_llvm_versions | last }}"
  # libc++
  - "libc++-{{ clang_llvm_versions | last }}-dev"
  - "libc++abi-{{ clang_llvm_versions | last }}-dev"
