---
clang_packages:
  # LLVM
  - "libllvm{{ clang_latest_llvm_version }}"
  - "llvm-{{ clang_latest_llvm_version }}"
  - "llvm-{{ clang_latest_llvm_version }}-dev"
  - "llvm-{{ clang_latest_llvm_version }}-doc"
  - "llvm-{{ clang_latest_llvm_version }}-examples"
  - "llvm-{{ clang_latest_llvm_version }}-runtime"
  # Clang and co
  - "clang-{{ clang_latest_llvm_version }}"
  - "clang-tools-{{ clang_latest_llvm_version }}"
  - "clang-{{ clang_latest_llvm_version }}-doc"
  - "libclang-common-{{ clang_latest_llvm_version }}-dev"
  - "libclang-{{ clang_latest_llvm_version }}-dev"
  - "libclang1-{{ clang_latest_llvm_version }}"
  - "clang-format-{{ clang_latest_llvm_version }}"
  - "python3-clang-{{ clang_latest_llvm_version }}"
  - "clangd-{{ clang_latest_llvm_version }}"
  - "clang-tidy-{{ clang_latest_llvm_version }}"
  # compiler-rt
  - "libclang-rt-{{ clang_latest_llvm_version }}-dev"
  # lldb
  - "lldb-{{ clang_latest_llvm_version }}"
  # lld (linker)
  - "lld-{{ clang_latest_llvm_version }}"
  # libc++
  - "libc++-{{ clang_latest_llvm_version }}-dev"
  - "libc++abi-{{ clang_latest_llvm_version }}-dev"
