---
clang_llvm_version: 18
clang_packages:
  - "llvm{{ clang_llvm_version }}"
  - "clang{{ clang_llvm_version }}"
  - "libclang-cpp{{ clang_llvm_version }}"
  - "clang-tools"
  - "python3-clang"
  - "lldb{{ clang_llvm_version }}"
  - "lld{{ clang_llvm_version }}"
