---
- name: "Web Applications | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      skip: true
  tags: webapplications

- name: "Web Applications | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ webapplications_packages }}"
    state: present
  tags: webapplications

- name: "Web Applications | Copy desktop files"
  tags: webapplications
  become: true
  block:
    - name: "Web Applications | Ensure applications directory exist"
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local/share/applications"
        state: directory
        owner: "{{ ansible_facts['user_uid'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: "0755"

    - name: "Web Applications | Copy desktop files"
      ansible.builtin.template:
        src: "webapp.desktop.j2"
        dest: "{{ ansible_user_dir }}/.local/share/applications/com.{{ item.key | lower }}.webapp.desktop"
        owner: "{{ ansible_facts['user_uid'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: "0644"
      loop: "{{ webapplications_apps | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
