---
- name: "VSCodium | Add repository"
  become: true
  ansible.builtin.deb822_repository:
    name: vscodium
    enabled: true
    types: deb
    uris: "https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/"
    suites: "vscodium"
    components:
      - main
    architectures:
      - "{{ deb_arch }}"
    signed_by: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg"

- name: "VSCodium | Update APT cache"
  become: true
  ansible.builtin.apt:
    update_cache: true
