---
- name: "Pre-commit | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: pre-commit

- name: "Pre-commit | Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ pre_commit_packages }}"
    state: present
  when: ansible_os_family in ['Archlinux', 'Suse']
  tags: pre-commit

- name: "Pre-commit | Install using Pipx"
  become: true
  community.general.pipx:
    name: "pre-commit"
    state: latest
    global: true
  when: ansible_os_family in ['Debian']
  tags: pre-commit
