---
- name: "Perl-Tidy | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: [perltidy, formatter, formatters]

- name: "Perl-Tidy | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ codespell_packages }}"
    update_cache: true
    state: present
  tags: [perltidy, formatter, formatters]
  when: perltidy_packages is defined
