---
- name: "Nodejs | Install dependencies [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.package:
    name: "{{ nodejs_dependencies }}"
    state: present

- name: "Nodejs | Add NodeSource deb repository - modern [{{ ansible_os_family }}]"
  when: ansible_version.full >= "2.15.0"
  ansible.builtin.include_tasks:
    file: debian-modern.yml
    apply:
      tags: nodejs

- name: "Nodejs | Add NodeSource deb repository - legacy [{{ ansible_os_family }}]"
  when: ansible_version.full < "2.15.0"
  ansible.builtin.include_tasks:
    file: debian-legacy.yml
    apply:
      tags: nodejs

- name: "Nodejs | Create preference files [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.template:
    src: preferences.j2
    dest: "/etc/apt/preferences.d/{{ item }}"
    mode: "0644"
  loop:
    - nsolid
    - nodejs
