---
- name: "Nodejs | Add NodeSource deb repository {{ ansible_os_family }}]"
  become: true
  ansible.builtin.deb822_repository:
    name: nodesource
    types: deb
    uris: "https://deb.nodesource.com/node_{{ nodejs_version }}.x"
    suites: "nodistro"
    components:
      - main
    architectures: "{{ deb_arch }}"
    signed_by: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
