---
- name: "Nodejs | Download GPG key"
  become: true
  ansible.builtin.get_url:
    url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
    dest: "/etc/apt/keyrings/nodesource.asc"
    mode: "0644"

- name: "Nodejs | Add NodeSource deb repository"
  become: true
  ansible.builtin.apt_repository:
    filename: nodejs
    repo: "deb [arch={{ deb_arch }} signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_{{ nodejs_version }}.x nodistro main"
    state: present
    update_cache: false
