---
- name: "NodeJS | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: nodejs

- name: "NodeJS | Add repository [{{ ansible_os_family }}]"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: nodejs
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: nodejs

- name: "Nodejs | Install package and npm [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.package:
    name:
      - nodejs
    update_cache: true
    state: present
  tags: nodejs
