---
- name: "NodeJS | Install [Debian]"
  ansible.builtin.import_tasks: setup-debian.yml
  when: ansible_os_family in [ "Debian" ]

- name: "NodeJS | Install [Rolling Release]"
  ansible.builtin.import_tasks: setup-rolling-release.yml
  when: ansible_os_family not in [ "Debian" ]
