---
- name: "nodejs | Install dependencies"
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    update_cache: true
    state: present

- name: "nodejs | Add NodeSource deb repository"
  become: true
  ansible.builtin.deb822_repository:
    name: nodesource
    types: deb
    uris: "https://deb.nodesource.com/node_{{ node_major }}.x"
    suites: "nodistro"
    components:
      - main
    architectures: "{{ deb_arch }}"
    signed_by: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"

- name: "nodejs | Create preference files"
  become: true
  template:
    src: preferences.j2
    dest: "/etc/apt/preferences.d/{{ item }}"
  loop:
    - nsolid
    - nodejs

- name: "nodejs | Install package and npm"
  become: true
  ansible.builtin.apt:
    name:
      - nodejs
    update_cache: true
    state: present
