---
- name: "Nodejs | Install dependencies [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.apt:
    name: "{{ nodejs_dependencies }}"
    update_cache: true
    state: present
  tags:
    - nodejs

- name: "Nodejs | Add NodeSource deb repository [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.deb822_repository:
    name: nodesource
    types: deb
    uris: "https://deb.nodesource.com/node_{{ nodejs_version }}.x"
    suites: "nodistro"
    components:
      - main
    architectures: "{{ deb_arch }}"
    signed_by: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
  tags:
    - nodejs

- name: "Nodejs | Create preference files [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.template:
    src: preferences.j2
    dest: "/etc/apt/preferences.d/{{ item }}"
    mode: "0644"
  loop:
    - nsolid
    - nodejs
  tags:
    - nodejs

- name: "Nodejs | Install package and npm [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.apt:
    name:
      - nodejs
    update_cache: true
    state: present
  tags:
    - nodejs
