---
- name: "Wireplumber | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags:
    - wireplumber

- name: "Wireplumber | Uninstall pipewire-media-session"
  become: true
  ansible.builtin.package:
    name: "pipewire-media-session"
    state: "absent"
  tags:
    - wireplumber

- name: "Wireplumber | Uninstall pipewire-media-session-docs"
  become: true
  ansible.builtin.package:
    name: "pipewire-media-session-docs"
    state: "absent"
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - wireplumber

- name: "Wireplumber | Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ wireplumber_packages }}"
    state: "present"
  when: wireplumber_packages is defined
  tags:
    - wireplumber

- name: "Wireplumber | Stop PulseAudio"
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: "stopped"
    scope: "user"
  when: "item in services"
  loop:
    - pulseaudio.socket
    - pulseaudio.service
  tags:
    - wireplumber

# - name: "Wireplumber | Uninstall PulseAudio"
#   become: true
#   ansible.builtin.packages:
#     name: "pulseaudio"
#     state: "absent"
#   tags:
#     - wireplumber

- name: "Wireplumber | Enable Pipewire and Wireplumber services"
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: "started"
    scope: "user"
  loop:
    - "pipewire"
    - "pipewire-pulse"
    - "wireplumber"
  tags:
    - wireplumber

- name: "Wireplumber | Copy configuration"
  tags:
    - wireplumber
  block:
    - name: "Wireplumber | Ensure configuration directory exists"
      ansible.builtin.file:
        path: "{{ wireplumber_user_dir }}"
        state: "directory"
        mode: "0755"

    - name: "Wireplumber | Copy configuration files"
      ansible.builtin.copy:
        src: "{{ role_path }}/files/"
        dest: "{{ wireplumber_user_dir }}"
        mode: "0644"
      notify: "Wireplumber | Restart Wireplumber service"
