---
- name: "Remove matcha temporary directory"
  ansible.builtin.file:
    path: "{{ themes_matcha_tmpdir.path }}"
    state: "absent"
  when: themes_matcha_tmpdir.path is defined

- name: "Remove catppuccin temporary directory"
  ansible.builtin.file:
    path: "{{ themes_catppuccin_tmpdir.path }}"
    state: "absent"
  when: themes_catppuccin_tmpdir.path is defined

- name: "Remove vimix temporary directory"
  ansible.builtin.file:
    path: "{{ themes_vimix_tmpdir.path }}"
    state: "absent"
  when: themes_vimix_tmpdir.path is defined
