---
- name: "Remove temporary directory"
  ansible.builtin.file:
    path: "{{ themes_matcha_tmpdir.path }}"
    state: "absent"
  when: themes_matcha_tmpdir.path is defined

- name: "Remove temporary directory"
  ansible.builtin.file:
    path: "{{ themes_catppuccin_tmpdir.path }}"
    state: "absent"
  when: themes_catppuccin_tmpdir.path is defined

- name: "Remove temporary directory"
  ansible.builtin.file:
    path: "{{ themes_vimix_tmpdir.path }}"
    state: "absent"
  when: themes_vimix_tmpdir.path is defined
