---
- name: "Icons | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: icons

- name: "Icons | Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ icons_packages }}"
    state: present
  tags: icons
