---
- name: "SDDM | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: sddm

- name: "SDDM | Install packages"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ sddm_packages }}"
  notify: "SDDM | Enable service"
  tags: sddm

- name: "SDDM | Setup Catppuccin theme"
  become: true
  when: sddm_theme_catppuccin_enabled
  tags: sddm
  block:
    - name: "SDDM | Get latest version number"
      register: sddm_catppuccin_latest_json
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ sddm_theme_catppuccin_gh_user }}/{{ sddm_theme_catppuccin_gh_repo }}/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json

    - name: "SDDM | Set facts"
      ansible.builtin.set_fact:
        sddm_catppuccin_latest_version: "{{ sddm_catppuccin_latest_json.json.tag_name[1:] }}"

    - name: "SDDM | Install Catppuccin theme"
      ansible.builtin.unarchive:
        src: "https://github.com/{{ sddm_theme_catppuccin_gh_user }}/{{ sddm_theme_catppuccin_gh_repo }}/releases/download/v{{
          sddm_catppuccin_latest_version }}/catppuccin-{{ sddm_theme_catppuccin_flavor }}-{{ sddm_theme_catppuccin_variant
          }}.zip"
        dest: "{{ sddm_themes_dir }}"
        owner: "root"
        group: "root"
        exclude:
          - "catppuccin-{{ sddm_theme_catppuccin_flavor }}-{{ sddm_theme_catppuccin_variant }}/preview.png"
        remote_src: true

    - name: "SDDM | Install configuration file"
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ sddm_config_dir }}/{{ item }}"
        owner: "root"
        group: "root"
        mode: "0644"
      loop:
        - "10-catppuccin-theme.conf"
