---
- name: "SDDM | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: sddm

- name: "SDDM | Install packages"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ sddm_packages }}"
  notify: "SDDM | Enable service"
  tags: sddm

- name: "SDDM | Setup Catppuccin theme"
  become: true
  when: sddm_theme.install.enabled
  tags: sddm
  block:
    - name: "SDDM | Get latest version number"
      register: sddm_catppuccin_latest_json
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ sddm_theme.catppuccin.gh_user }}/{{ sddm_theme.catppuccin.gh_repo }}/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json

    - name: "SDDM | Set facts"
      ansible.builtin.set_fact:
        sddm_catppuccin_latest_version: "{{ sddm_catppuccin_latest_json.json.tag_name[1:] }}"
      tags: nerdfonts

    - name: "SDDM | Install Catppuccin theme"
      ansible.builtin.unarchive:
        src: "https://github.com/{{ sddm_theme.catppuccin.gh_user }}/{{ sddm_theme.catppuccin.gh_repo }}/releases/download/v{{
          sddm_catppuccin_latest_version }}/catppuccin-{{ sddm_theme.catppuccin.flavor }}-{{ sddm_theme.catppuccin.variant
          }}.zip"
        dest: "{{ sddm_themes_dir }}"
        owner: "root"
        group: "root"
        exclude:
          - "catppuccin-{{ sddm_theme.catppuccin.flavor }}-{{ sddm_theme.catppuccin.variant }}/preview.png"
        remote_src: true
