---
- name: "Python | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: python

- name: "Python | Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ python_packages }}"
    state: present
  when: python_packages is defined
  tags: python
