---
- name: "Clang | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: clang

- name: "Conky | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ conky_packages }}"
    state: present
  tags: conky

- name: "Conky | Get number of CPU cores"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      lscpu | grep -E '^Core' | awk '{ print $4 }'
  register: cpu_core_number
  changed_when: cpu_core_number.rc != 0
  tags: conky

- name: "Conky | Get number of CPU threads"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      lscpu | grep -E '^CPU\(' | awk '{ print $2 }'
  register: cpu_number
  changed_when: cpu_number.rc != 0
  tags: conky

- name: "Conky | Get coretemp number in /sys"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      ls /sys/devices/platform/coretemp.0/hwmon/
  register: coretemp_hwmon
  changed_when: coretemp_hwmon.rc != 0
  tags: conky

- name: "Conky | Set CPU facts"
  ansible.builtin.set_fact:
    cpu_core_count: "{{ cpu_core_number.stdout_lines[0] }}"
    cpu_count: "{{ cpu_number.stdout_lines[0] }}"
    coretemp_hwmon_number: "{{ coretemp_hwmon.stdout_lines[0][-1] }}"
  tags: conky

- name: "Conky | Copy configuration files"
  ansible.builtin.include_tasks:
    file: copy-conf.yml
    apply:
      tags: conky
  tags: conky
