---
- name: "Black | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: [black, formatter]

- name: "Black | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ black_packages }}"
    update_cache: true
    state: present
  tags: [black, formatter]
  when: black_packages is defined

- name: "Black | Install from source"
  become: true
  community.general.pipx:
    name: "black"
    state: latest
    global: true
  tags: [black, formatter]
  when: black_packages is not defined
