---
- name: "Xfce4 | Ensure colorschemes directory exists"
  become: true
  ansible.builtin.file:
    path: "{{ xfce4_terminal_coloschemes_dir }}"
    state: directory
    mode: "0755"
  tags:
    - xfce
    - xfce4

- name: "Xfce4 | Install catppuccin themes for terminal"
  become: true
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/catppuccin/xfce4-terminal/refs/heads/main/themes/catppuccin-{{ item }}.theme"
    dest: "{{ xfce4_terminal_coloschemes_dir }}"
    mode: "0644"
  loop:
    - frappe
    - latte
    - macchiato
    - mocha
  tags:
    - xfce
    - xfce4

- name: "Xfce4 | Ensure colorschemes directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/xfce4"
    state: directory
    mode: "0755"
  tags:
    - xfce
    - xfce4

- name: "Xfce4 | Copy configuration files" # noqa risky-file-permissions
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_user_dir }}/.config/xfce4"
  tags:
    - xfce
    - xfce4
