---
- name: "Wireshark | Add PPA"
  become: true
  ansible.builtin.deb822_repository:
    name: wireshark
    enabled: true
    types: deb
    uris: "https://ppa.launchpadcontent.net/wireshark-dev/stable/ubuntu"
    suites: "{{ ansible_distribution_release | lower }}"
    components:
      - main
