---
- name: "Wireshark | Add PPA"
  become: true
  ansible.builtin.deb822_repository:
    name: wireshark
    enabled: true
    types: deb
    uris: "https://ppa.launchpadcontent.net/wireshark-dev/stable/ubuntu"
    suites: "{{ ansible_facts.distribution_release | lower }}"
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa2e402b85a4b70cd78d8a3d9d875551314eca0f0"
    components:
      - main

- name: "Wireshark | Update APT cache"
  become: true
  ansible.builtin.apt:
    update_cache: true
