---
- name: "Include OS specific variables"
  ansible.builtin.include_vars: "{{ ansible_facts.os_family | lower }}.yml"
  tags: yazi

- name: "Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ yazi_packages }}"
    state: "present"
  when: yazi_packages is defined
  tags: yazi

- name: "Ensure configuration directory exists"
  ansible.builtin.file:
    path: "{{ yazi_config_dir }}"
    state: "directory"
    mode: "0755"
  notify:
    - "Yazi | Download Catppuccin Mocha theme (peach variant)"
  tags: yazi

- name: "Copy configuration files"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ yazi_config_dir }}"
    mode: "0644"
  tags: yazi
