---
- name: "Nextcloud | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: nextcloud

- name: "Nextcloud | Add repository [{{ ansible_os_family }}]"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: nextcloud
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: nextcloud

- name: "Nextcloud | Install packages"
  become: true
  when: nextcloud_packages is defined
  ansible.builtin.package:
    name: "{{ nextcloud_packages }}"
    state: present
  tags: nextcloud

- name: "Nextcloud | Start service file"
  become: true
  tags: nextcloud
  block:
    - name: "Nextcloud | Ensure directory exists"
      ansible.builtin.file:
        path: "/usr/local/lib/systemd/user"
        state: directory
        mode: "0755"

    - name: "Nextcloud | Copy service file"
      ansible.builtin.copy:
        src: "nextcloud.service"
        dest: "/usr/local/lib/systemd/user"
        mode: "0644"

    - name: "Nextcloud | Enable service"
      become: false
      ansible.builtin.systemd:
        name: "nextcloud"
        daemon_reload: true
        enabled: true
        scope: "user"
