---
- name: "Ripgrep | Install bash completion file"
  become: true
  block:
    - name: "Ripgrep | Ensure bash-completion directory exists"
      ansible.builtin.file:
        path: "/usr/local/share/bash-completion/completions"
        state: directory
        mode: "0755"

    - name: "Ripgrep | Install completion file"
      ansible.builtin.shell:
        cmd: "rg --generate complete-bash > /usr/local/share/bash-completion/completions/ripgrep"
        creates: "/usr/local/share/bash-completion/completions/ripgrep"

- name: "Ripgrep | Install zsh completion file"
  become: true
  block:
    - name: "Ripgrep | Ensure zsh-completion directory exists"
      ansible.builtin.file:
        path: "/usr/local/share/zsh/site-functions"
        state: directory
        mode: "0755"

    - name: "Ripgrep | Install completion file"
      ansible.builtin.shell:
        cmd: "rg --generate complete-zsh > /usr/local/share/zsh/site-functions/_ripgrep"
        creates: "/usr/local/share/zsh/site-functions/_ripgrep"
