---
- name: "Ripgrep | Install completions"
  ansible.builtin.include_tasks:
    file: completions.yml
  loop:
    - shell: zsh
      filepath: "{{ ansible_user_dir }}/.local/share/zsh/site-functions/_ripgrep"
    - shell: bash
      filepath: "{{ ansible_user_dir }}/.local/share/bash-completion/completions/ripgrep"
