---
- name: "Libreoffice | Add PPA"
  become: true
  ansible.builtin.deb822_repository:
    name: libreoffice
    enabled: true
    types: deb
    uris: "https://ppa.launchpadcontent.net/libreoffice/ppa/ubuntu"
    suites: "{{ ansible_facts['distribution_release'] | lower }}"
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcdde43ba4de3f09d7ce7016673aee920ad55f5a0"
    components:
      - main
