---
- name: "Libreoffice | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: libreoffice

- name: "Libreoffice | Include OS specific tasks"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: libreoffice
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: libreoffice

- name: "Libreoffice | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ libreoffice_packages }}"
    state: present
  when: libreoffice_packages is defined
  tags: libreoffice
