---
- name: "Zellij | Ensure completion directory exists [{{ item.shell }}]"
  become: true
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory
    mode: "0755"
  vars:
    install_dir: "{{ item.filepath | ansible.builtin.dirname }}"

- name: "Zellij | Install completion file [{{ item.shell }}]"
  become: true
  ansible.builtin.shell:
    cmd: "zellij setup --generate-completion {{ item.shell }} > {{ item.filepath }}"
  register: output
  changed_when: output.rc != 0
