---
- name: "Zellij | Install completion"
  ansible.builtin.include_tasks:
    file: completions.yml
  loop:
    - shell: zsh
      filepath: "/usr/local/share/zsh/site-functions/_zellij"
    - shell: bash
      filepath: "/usr/local/share/bash-completion/completions/zellij"
