---
- name: "Podman | Install repository [{{ ansible_facts.os_family }}]"
  become: true
  ansible.builtin.deb822_repository:
    name: "podman"
    enabled: true
    types: deb
    uris: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_facts.distribution_version }}"
    suites: "/"
    signed_by: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_facts.distribution_version }}/Release.key"

- name: "Podman | Update APT cache"
  become: true
  ansible.builtin.apt:
    update_cache: true
