---
- name: "Podman | Download GPG key"
  become: true
  ansible.builtin.get_url:
    url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_distribution_version }}/Release.key"
    dest: "/etc/apt/keyrings/devel:kubic:libcontainers:stable.asc"
    mode: "0644"

- name: "Podman | Add deb repository"
  become: true
  ansible.builtin.apt_repository:
    filename: "devel:kubic:libcontainers:stable"
    repo:
      "deb [signed-by=/etc/apt/keyrings/devel:kubic:libcontainers:stable.asc] \
      https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_distribution_version }}/Release.key \
      /"
    state: present
    update_cache: false
