---
- name: "Podman | Install repository [Debian]"
  become: true
  ansible.builtin.deb822_repository:
    name: "podman"
    enabled: true
    types: deb
    uris: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_facts['distribution']_version
      }}"
    suites: "/"
    signed_by: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_facts['distribution']_version
      }}/Release.key"
