---
- name: "Podman | Add deb repository - modern"
  when: ansible_version.full >= "2.15.0"
  ansible.builtin.include_tasks:
    file: debian-modern.yml
    apply:
      tags: podman

- name: "Podman | Add deb repository - legacy"
  when: ansible_version.full < "2.15.0"
  ansible.builtin.include_tasks:
    file: debian-legacy.yml
    apply:
      tags: podman
