---
- name: "Podman | Check that it is supported by the OS"
  ansible.builtin.assert:
    that:
      - ansible_facts.system == "Linux"

- name: "Podman | Install packages"
  become: true
  ansible.builtin.package:
    state: present
    name: "podman"
  tags: podman
