---
- name: "Nerdfonts | Check if font exists [{{ item }}]"
  ansible.builtin.stat:
    path: "{{ nerdfonts_font_dir_prefix }}/{{ item }}"
  register: font_exists

- name: "Nerdfonts | Ensure font directory exists [{{ item }}]"
  when: not font_exists.stat.exists
  ansible.builtin.file:
    path: "{{ nerdfonts_font_dir_prefix }}/{{ item }}"
    mode: "0755"
    state: directory
  become: true

- name: "Nerdfonts | Download fonts [{{ item }}]"
  when: not font_exists.stat.exists
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ nerdfonts_latest_version }}/{{ item }}.tar.xz"
    dest: "{{ nerdfonts_font_dir_prefix }}/{{ item }}"
    mode: "0644"
    remote_src: true
  become: true
