---
- name: "Nerdfonts | Ensure font directory exists [{{ item }}]"
  become: true
  ansible.builtin.file:
    path: "{{ nerdfonts_font_dir_prefix }}/{{ item }}"
    recurse: true
    mode: "0755"
    state: directory

- name: "Nerdfonts | Download fonts [{{ item }}]"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ nerdfonts_latest_version }}/{{ item }}.tar.xz"
    dest: "{{ nerdfonts_font_dir_prefix }}/{{ item }}"
    mode: "0644"
    remote_src: true
    owner: "root"
    group: "root"
  notify: "Nerdfonts | Build font information caches"
