---
- name: "Nerdfonts | Check if font exists [{{ item }}]"
  ansible.builtin.stat:
    path: "{{ nerdfonts_font_dir_prefix }}/{{ item }}"
  register: font_exists

- name: "Nerdfonts | Install font [{{ item }}]"
  when: not font_exists.stat.exists
  become: true
  block:
    - name: "Nerdfonts | Ensure font directory exists [{{ item }}]"
      ansible.builtin.file:
        path: "{{ nerdfonts_font_dir_prefix }}/{{ item }}"
        mode: "0755"
        state: directory

    - name: "Nerdfonts | Download fonts [{{ item }}]"
      ansible.builtin.unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ nerdfonts_latest_version }}/{{ item }}.tar.xz"
        dest: "{{ nerdfonts_font_dir_prefix }}/{{ item }}"
        mode: "0644"
        remote_src: true
