---
- name: "Nerdfonts | Get latest version number"
  register: latest_json
  ansible.builtin.uri:
    url: "https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest"
    method: GET
    return_content: true
    status_code: 200
    body_format: json
  tags: nerdfonts

- name: "Nerdfonts | Set facts"
  ansible.builtin.set_fact:
    nerdfonts_latest_version: "{{ latest_json.json.tag_name[1:] }}"
  tags: nerdfonts

- name: "Nerdfonts | Ensure fonts directory exists"
  become: true
  ansible.builtin.file:
    path: "{{ nerdfonts_font_dir_prefix }}"
    state: directory
    mode: "0755"
  tags: nerdfonts

- name: "Nerdfonst | Download fonts if necessary [v{{ nerdfonts_latest_version }}]"
  ansible.builtin.include_tasks:
    file: font-download.yml
    apply:
      tags: nerdfonts
  loop:
    - "Hack"
    - "Iosevka"
    - "Meslo"
    - "Ubuntu"
    - "UbuntuMono"
  tags: nerdfonts

- name: "Nerdfonts | Build font information caches"
  ansible.builtin.command: fc-cache --force --verbose
  become: true
  changed_when: false
  tags: nerdfonts
