---
- name: "Nerdfonts | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags: docker

- name: "Nerdfonts | Install packages"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ nerdfonts_packages }}"
  when: nerdfonts_packages is defined
  tags: nerdfonts

- name: "Nerdfonts | Install from source"
  when: nerdfonts_packages is not defined
  tags: nerdfonts
  block:
    - name: "Nerdfonts | Get latest version number"
      register: nerdfonts_latest_json
      ansible.builtin.uri:
        url: "https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json

    - name: "Nerdfonts | Set facts"
      ansible.builtin.set_fact:
        nerdfonts_latest_version: "{{ nerdfonts_latest_json.json.tag_name[1:] }}"
      tags: nerdfonts

    - name: "Nerdfonts | Download fonts"
      ansible.builtin.include_tasks:
        file: font-download.yml
        apply:
          tags: nerdfonts
      loop: "{{ nerdfonts_list }}"
      tags: nerdfonts
