---
- name: "ZSH | Install shell"
  ansible.builtin.include_tasks: zsh.yml
  tags:
    - shell
    - zsh

- name: "ZSH | Install oh-my-zsh, its plugins and themes"
  ansible.builtin.include_tasks: oh-my-zsh.yml
  tags:
    - shell
    - omz
    - p10k

- name: "Shell | Copy configuration file"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: "0644"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
  loop:
    - zshrc
    - p10k.zsh
  tags:
    - shell
    - omz
    - p10k
