---
- name: "ZSH | Install shell"
  ansible.builtin.include_tasks:
    file: zsh.yml
    apply:
      tags:
        - shell
        - zsh
  tags:
    - shell
    - zsh

- name: "ZSH | Install oh-my-zsh, its plugins and themes"
  ansible.builtin.include_tasks:
    file: oh-my-zsh.yml
    apply:
      tags:
        - shell
        - zsh
        - omz
  tags:
    - shell
    - zsh
    - omz

- name: "Shell | Copy configuration file"
  tags:
    - shell
    - zsh
    - omz
    - p10k
  block:
    - name: "Shell | Copy static configuration file"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/.{{ item }}"
        mode: "0644"
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
      loop:
        - zshrc
        - p10k.zsh
        - xprofile
        - Xresources

    - name: "Shell | Copy dynamic configuration file"
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ ansible_user_dir }}/.{{ item }}"
        mode: "0644"
      loop:
        - zprofile
