---
- name: "Oh My Zsh | Install Oh My Zsh"
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ zsh_omz_dir }}"
    version: "master"
    update: true

- name: "Oh My Zsh | Install ZSH plugins"
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ zsh_omz_custom_dir }}/plugins/{{ item.dest }}"
    version: "master"
    update: true
  loop:
    - repo: "https://github.com/zsh-users/zsh-autosuggestions"
      dest: "zsh-autosuggestions"
    - repo: "https://github.com/zsh-users/zsh-completions"
      dest: "zsh-completions"
    - repo: "https://github.com/zsh-users/zsh-history-substring-search"
      dest: "zsh-history-substring-search"
    - repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
      dest: "zsh-syntax-highlighting"
    - repo: "https://github.com/MichaelAquilina/zsh-you-should-use"
      dest: "you-should-use"

- name: "Oh My Zsh | Install powerlevel10k theme"
  ansible.builtin.git:
    repo: "https://gitee.com/romkatv/powerlevel10k.git"
    dest: "{{ omz_custom_dir }}/themes/powerlevel10k"
    version: "master"
    update: true
