---
# tasks file for shell
- name: "Shell | Install zsh package"
  become: true
  ansible.builtin.package:
    name:
      - zsh
    state: present

- name: "Shell | Ensure zsh is the default shell"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "/usr/bin/zsh"
  become: true
