---
# tasks file for shell
- name: "Install zsh package"
  become: true
  ansible.builtin.package:
    name:
      - zsh
    state: present

- name: "Ensure zsh is the default shell"
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    shell: "/usr/bin/zsh"
  become: true
