---
- name: "TexLab Language Server | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags:
    - lsp
    - texlab

- name: "TexLab Language Server | Install from package manager"
  become: true
  when: texlab_package is defined
  ansible.builtin.package:
    name: "{{ texlab_package }}"
    state: present
  tags:
    - lsp
    - texlab

- name: "TexLab Language Server | Install from GitHub"
  when: texlab_package is not defined
  tags:
    - lsp
    - texlab
  block:
    - name: "TexLab Language Server | Get latest version number"
      register: texlab_latest_json
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ texlab_github_user }}/{{ texlab_github_repo }}/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json

    - name: "TexLab Language Server | Set facts"
      ansible.builtin.set_fact:
        texlab_latest_version: "{{ texlab_latest_json.json.tag_name[1:] }}"

    - name: "TexLab Language Server | Install executable"
      become: true
      ansible.builtin.unarchive:
        src: "https://github.com/{{ texlab_github_user }}/{{ texlab_github_repo }}/releases/download/v{{ texlab_latest_version
          }}/texlab-{{ ansible_facts.architecture }}-{{ ansible_facts.system | lower }}.tar.gz"
        dest: "{{ ansible_facts.user_dir }}/.local/bin"
        owner: "{{ ansible_facts.user_uid }}"
        group: "{{ ansible_facts.user_gid }}"
        mode: "0755"
        include:
          - "texlab"
        remote_src: true
