---
- name: "TexLab Language Server | Get latest version number"
  register: latest_json
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ texlab_github_user }}/{{ texlab_github_repo }}/releases/latest"
    method: GET
    return_content: true
    status_code: 200
    body_format: json

- name: "TexLab Language Server | Set facts"
  ansible.builtin.set_fact:
    texlab_latest_version: "{{ latest_json.json.tag_name[1:] }}"

- name: "TexLab Language Server | Install executable"
  become: true
  ansible.builtin.unarchive:
    src:
      "https://github.com/{{ texlab_github_user }}/{{ texlab_github_repo }}/releases/download/v{{ texlab_latest_version }}/\
      texlab-{{ ansible_architecture }}-{{ ansible_system | lower }}.tar.gz"
    dest: "/usr/local/bin"
    mode: "0755"
    include:
      - "texlab"
    remote_src: true
