---
- name: "Network Manager | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: [networkmanager, nmcli]

- name: "Network Manager | Install dependencies"
  become: true
  ansible.builtin.package:
    name: "{{ network_packages }}"
    state: "present"
  tags: [networkmanager, nmcli]

- name: "Network Manager | Enable service"
  become: true
  ansible.builtin.systemd:
    name: "NetworkManager.service"
    enabled: true
    state: "started"
  tags: [networkmanager, nmcli]

- name: "Network Manager | Install ethernet configurations"
  become: true
  community.general.nmcli:
    type: ethernet
    conn_name: "{{ item.name }}"
    ifname: ""
    method4: auto
    method6: auto
    state: present
  loop: "{{ network_ethernet_connections }}"
  tags: [networkmanager, nmcli]

- name: "Network Manager | Install wifi configurations"
  community.general.nmcli:
    type: wifi
    conn_name: "{{ item.name }}"
    ssid: "{{ item.name }}"
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ item.psk }}"
    autoconnect: "{{ item.autoconnect }}"
    state: present
  loop: "{{ network_wifi_connections }}"
  tags: [networkmanager, nmcli]
