---
- name: "Spotify | Include OS specific tasks"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: spotify
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: spotify
