---
- name: "Rustup | Get active toolchain version"
  ansible.builtin.shell:
    cmd: |
      rustup default | awk '{ print $1 }'
  register: rustup_get_default_output
  environment:
    RUSTUP_HOME: "{{ ansible_user_dir }}/.rustup"
    CARGO_HOME: "{{ ansible_user_dir }}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.cargo/bin"
  changed_when: false
  ignore_errors: true

- name: "Rustup | Set default toolchain version"
  ansible.builtin.command:
    cmd: rustup default "{{ rustup_default_version }}"
  environment:
    RUSTUP_HOME: "{{ ansible_user_dir }}/.rustup"
    CARGO_HOME: "{{ ansible_user_dir }}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.cargo/bin"
  register: rustup_set_default_output
  failed_when: rustup_set_default_output.rc != 0
  changed_when:
    - rustup_set_default_output.rc == 0
    - "'unchanged' not in rustup_set_default_output.stdout"

- name: "Rustup | Update Rust toolchain"
  ansible.builtin.command:
    cmd: "rustup update"
  environment:
    RUSTUP_HOME: "{{ ansible_user_dir }}/.rustup"
    CARGO_HOME: "{{ ansible_user_dir }}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.cargo/bin"
  register: rustup_update
  failed_when: rustup_update.rc != 0
  changed_when:
    - rustup_update.rc == 0
    - (rustup_get_default_output.stdout_lines[0] ~ " updated") in rustup_update.stdout
