---
- name: "Rustup | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: rustup

- name: "Rustup | Install dependencies"
  become: true
  ansible.builtin.package:
    name: "{{ rustup_dependencies }}"
    state: present
  when: rustup_dependencies is defined
  tags: rustup

- name: "Rustup | Install from script"
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: rustup
  tags: rustup

- name: "Rustup | Install toolchain"
  ansible.builtin.include_tasks:
    file: install-toolchain.yml
    apply:
      tags: rustup
  tags: rustup
