---
- import_tasks: package.yml
  when: ansible_os_family in ['Archlinux', 'Suse']

- import_tasks: install.yml
  when: ansible_os_family not in ['Archlinux', 'Suse']

- import_tasks: install-toolchain.yml
