---
- name: "Rustup | Uninstall rust from package manager"
  become: true
  ansible.builtin.package:
    name:
      - rust
    state: absent

- name: "Rustup | Install from package manager"
  become: true
  ansible.builtin.package:
    name:
      - rustup
    state: present
