---
- name: "Clang | Create LLVM alternatives list"
  ansible.builtin.set_fact:
    clang_alternatives_llvm_config_full: |-
      [
      {% for alt in clang_alternatives_llvm_config %}
         {
           "name": "{{ alt }}",
           "link": "/usr/bin/{{ alt }}"
           "path": "/usr/bin/{{ alt }}-{{ clang_llvm_stable_version }}"
         },
      {% endfor %}
      ]

- name: "Clang | Print"
  ansible.builtin.debug:
    var: clang_alternatives_llvm_config_full

- name: "Clang | Update Clang and LLVM alternatives [{{ ansible_os_family }}]"
  become: true
  block:
    - name: "Clang | Update LLVM alternatives [{{ ansible_os_family }}]"
      community.general.alternatives:
        name: llvm-config
        link: /usr/bin/llvm-config
        path: "/usr/bin/llvm-config-{{ clang_llvm_stable_version }}"
        priority: 100
        subcommands: "{{ clang_alternatives_llvm_config_full | to_yaml }}"

    - name: "Clang | Update Clang alternatives [{{ ansible_os_family }}]"
      community.general.alternatives:
        name: clang
        link: /usr/bin/clang
        path: "/usr/bin/clang-{{ clang_llvm_stable_version }}"
        priority: 100
        subcommands:
          - name: clang++
            link: /usr/bin/clang++
            path: "/usr/bin/clang++-{{ clang_llvm_stable_version }}"
          - name: asan_symbolize
            link: /usr/bin/asan_symbolize
            path: "/usr/bin/asan_symbolize-{{ clang_llvm_stable_version }}"
          - name: c-index-test
            link: /usr/bin/c-index-test
            path: "/usr/bin/c-index-test-{{ clang_llvm_stable_version }}"
          - name: clang-check
            link: /usr/bin/clang-check
            path: "/usr/bin/clang-check-{{ clang_llvm_stable_version }}"
          - name: clang-cl
            link: /usr/bin/clang-cl
            path: "/usr/bin/clang-cl-{{ clang_llvm_stable_version }}"
          - name: clang-cpp
            link: /usr/bin/clang-cpp
            path: "/usr/bin/clang-cpp-{{ clang_llvm_stable_version }}"
          - name: clang-format
            link: /usr/bin/clang-format
            path: "/usr/bin/clang-format-{{ clang_llvm_stable_version }}"
          - name: clang-format-diff
            link: /usr/bin/clang-format-diff
            path: "/usr/bin/clang-format-diff-{{ clang_llvm_stable_version }}"
          - name: clang-import-test
            link: /usr/bin/clang-import-test
            path: "/usr/bin/clang-import-test-{{ clang_llvm_stable_version }}"
          - name: clang-include-fixer
            link: /usr/bin/clang-include-fixer
            path: "/usr/bin/clang-include-fixer-{{ clang_llvm_stable_version }}"
          - name: clang-offload-bundler
            link: /usr/bin/clang-offload-bundler
            path: "/usr/bin/clang-offload-bundler-{{ clang_llvm_stable_version }}"
          - name: clang-query
            link: /usr/bin/clang-query
            path: "/usr/bin/clang-query-{{ clang_llvm_stable_version }}"
          - name: clang-rename
            link: /usr/bin/clang-rename
            path: "/usr/bin/clang-rename-{{ clang_llvm_stable_version }}"
          - name: clang-reorder-fields
            link: /usr/bin/clang-reorder-fields
            path: "/usr/bin/clang-reorder-fields-{{ clang_llvm_stable_version }}"
          - name: clang-tidy
            link: /usr/bin/clang-tidy
            path: "/usr/bin/clang-tidy-{{ clang_llvm_stable_version }}"
          - name: lldb
            link: /usr/bin/lldb
            path: "/usr/bin/lldb-{{ clang_llvm_stable_version }}"
          - name: lldb-server
            link: /usr/bin/lldb-server
            path: "/usr/bin/lldb-server-{{ clang_llvm_stable_version }}"
