---
- name: "Clang | Install certificate"
  become: true
  ansible.builtin.get_url:
    url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    dest: "/etc/apt/keyrings/apt.llvm.org.asc"
    mode: "0644"

- name: "Clang | Install source repository"
  become: true
  ansible.builtin.deb822_repository:
    name: "llvm-{{ item }}"
    enabled: true
    types: deb
    uris: "http://apt.llvm.org/{{ ansible_distribution_release }}"
    suites: "llvm-toolchain-{{ ansible_distribution_release }}-{{ item }}"
    components: main
    state: present
    signed_by: "/etc/apt/keyrings/apt.llvm.org.asc"
  loop: "{{ clang_llvm_versions }}"
