---
- name: "Clang | Download GPG key"
  become: true
  ansible.builtin.get_url:
    url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    dest: "/etc/apt/keyrings/llvm.asc"
    mode: "0644"

- name: "Clang | Add deb repository"
  become: true
  ansible.builtin.apt_repository:
    filename: llvm
    repo: "deb [signed-by=/etc/apt/keyrings/llvm.asc] \
      http://apt.llvm.org/{{ ansible_distribution_release }} \
      llvm-toolchain-{{ ansible_distribution_release }}-{{ clang_llvm_stable_version }} main"
    state: present
    update_cache: false
