---
- name: "Clang | Install dependencies [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ clang_dependencies }}"

- name: "Clang | Add deb repository - modern"
  when: ansible_version.full >= "2.15.0"
  ansible.builtin.include_tasks:
    file: debian-modern.yml
    apply:
      tags: clang

- name: "Clang | Add deb repository - legacy"
  when: ansible_version.full < "2.15.0"
  ansible.builtin.include_tasks:
    file: debian-legacy.yml
    apply:
      tags: clang
