---
- name: "Clang | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family | lower }}.yml"
      skip: true

- name: "Clang | Add LLVM repository [Debian]"
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: "Clang | Install LLVM packages"
  become: true
  ansible.builtin.package:
    update_cache: true
    state: present
    name: "{{ clang_packages }}"
