---
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: "Clang | Install LLVM packages [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.package:
    name:
      - clang
  when: ansible_os_family == 'Archlinux'

- name: "Clang | Install LLVM packages [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.package:
    name:
      - llvm
  when: ansible_os_family in ['Suse', 'FreeBSD']
