---
- name: "Clang | Add LLVM repository [Debian]"
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: "Clang | Install LLVM packages [Archlinux]"
  become: true
  ansible.builtin.package:
    name:
      - clang
  when: ansible_os_family == 'Archlinux'

- name: "Clang | Install LLVM packages [Suse, FreeBSD]"
  become: true
  ansible.builtin.package:
    name:
      - llvm
  when: ansible_os_family in ['Suse', 'FreeBSD']
