---
- name: "Clang | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: clang

- name: "Clang | Add LLVM repository"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: clang
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: clang

- name: "Clang | Install LLVM packages"
  become: true
  ansible.builtin.package:
    update_cache: true
    state: present
    name: "{{ clang_packages }}"
  tags: clang

- name: "Clang | Update Clang and LLVM alternatives [Debian]"
  when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks:
    file: alternatives.yml
    apply:
      tags: clang
  tags: clang

- name: "Clangd | Copy configuration file"
  tags: [clang, clangd]
  block:
    - name: "Clangd | Ensure configuration directory exists"
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/clangd"
        mode: "0755"
        state: "directory"

    - name: "Clangd | Copy launcher script"
      ansible.builtin.copy:
        src: "config.yaml"
        dest: "{{ clang_clangd_config_dir }}"
        mode: "0755"
