---
driver:
  name: docker

platforms:
  - name: wlprop-debian
    image: debian:12

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml

verifier:
  name: testinfra
