---
- name: "Ripgrep | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags:
    - ripgrep

- name: "Ripgrep | Install Rust package with locked dependencies"
  community.general.cargo:
    name: ripgrep
    state: latest
    locked: true
  notify: "Ripgrep | Install completions"
  tags: ripgrep
  when: ripgrep_packages is not defined

- name: "Ripgrep | Install from package manager [{{ ansible_facts.os_family }}]"
  become: true
  ansible.builtin.package:
    name: "{{ ripgrep_packages }}"
  when: ripgrep_packages is defined
  tags:
    - ripgrep
