---
- name: "Ripgrep | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags:
    - ripgrep

- name: "Ripgrep | Install Rust package with locked dependencies"
  become: true
  community.general.cargo:
    name: ripgrep
    state: latest
    locked: true
    path: "/usr/local"
  environment:
    RUSTUP_HOME: "{{ ansible_user_dir }}/.rustup"
    CARGO_HOME: "{{ ansible_user_dir }}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.cargo/bin"
  notify: "Ripgrep | Install completions"
  tags: ripgrep
  when: ripgrep_packages is not defined

- name: "Ripgrep | Install from package manager [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.package:
    name: "{{ ripgrep_packages }}"
  when: ripgrep_packages is defined
  tags:
    - ripgrep
