---
# tasks file for shell
- name: "FZF | Install from sources"
  ansible.builtin.import_tasks: source-install.yml
  when: ansible_os_family == "Debian"

- name: "FZF | Install from package manager"
  ansible.builtin.import_tasks: package-install.yml
  when: ansible_os_family != "Debian"
