---
- name: "Discord | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      skip: true
  tags: fzf

- name: "FZF | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ fzf_packages }}"
  when: fzf_packages is defined
  tags: fzf

- name: "FZF | Install from sources"
  ansible.builtin.include_tasks:
    file: source.yml
    apply:
      tags: fzf
  when: fzf_packages is not defined
  tags: fzf
