---
- name: "fzf | Install binary file into {{ direnv_bin_install_dir }}"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/junegunn/fzf/releases/download/v{{ fzf_version }}/fzf-{{ fzf_version }}-{{ ansible_system | lower }}_{{ alt_arch }}.tar.gz"
    dest: "{{ fzf_bin_install_dir }}"
    remote_src: true

- name: "fzf | Install man pages into {{ direnv_man_install_dir }}"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/junegunn/fzf/archive/refs/tags/v{{ fzf_version }}.tar.gz"
    dest: "{{ fzf_man_install_dir }}/man1"
    remote_src: true
    keep_newer: true
    include:
      - "fzf-{{ fzf_version }}/man/man1/fzf.1"
      - "fzf-{{ fzf_version }}/man/man1/fzf-tmux.1"
    extra_opts:
      - "--strip-components=3"
