---
- name: "Git | Add PPA"
  become: true
  ansible.builtin.deb822_repository:
    name: git-core
    enabled: true
    types: deb
    uris: "https://ppa.launchpadcontent.net/git-core/ppa/ubuntu"
    suites: "{{ ansible_facts['distribution_release'] | lower }}"
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf911ab184317630c59970973e363c90f8f1b6217"
    components:
      - main
