---
- name: "Git | Add PPA"
  become: true
  ansible.builtin.deb822_repository:
    name: git-core
    enabled: true
    types: deb
    uris: "https://ppa.launchpadcontent.net/git-core/ppa/ubuntu"
    suites: "{{ ansible_facts['distribution_release'] | lower }}"
    components:
      - main
