---
- name: "Git | Add PPA [{{ ansible_os_family }}]"
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:git-core/ppa"
    codename: "{{ ansible_distribution_release }}"
    state: present
    update_cache: true
