---
- name: "Git | Add PPA"
  become: true
  ansible.builtin.apt_repository:
    filename: git-core
    repo: "ppa:git-core/ppa"
    codename: "{{ ansible_distribution_release }}"
    state: present
    update_cache: false
