---
- name: "Git | Set distro-specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - "main.yml"

- name: "Git | Install repository [Debian]"
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: "Git | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ git_package }}"
    state: present
