---
- name: "Themes | Ensure directory exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  tags:
    - themes
    - theming
  loop:
    - "{{ themes_gtk_dir }}"
    - "{{ themes_gtk3_config_dir }}"
    - "{{ themes_gtk4_config_dir }}"

- name: "Themes | Install dependencies"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ themes_packages }}"
  when: themes_packages_dependencies is defined
  tags:
    - themes
    - theming

- name: "Themes | Install Matcha themes"
  ansible.builtin.include_tasks:
    file: "matcha.yml"
    apply:
      tags:
        - themes
        - theming
  when: themes_matcha_enable
  tags:
    - themes
    - theming

- name: "Themes | Install Catppuccin themes"
  ansible.builtin.include_tasks:
    file: "catppuccin.yml"
    apply:
      tags:
        - themes
        - theming
  when: themes_catppuccin_enable
  tags:
    - themes
    - theming
