---
- name: "NPMrc | Install NPM configuration file"
  tags: npmrc
  ansible.builtin.template:
    src: "npmrc.j2"
    dest: "{{ ansible_facts['user_dir'] }}/.npmrc"
    mode: "0644"

- name: "NPMrc | Create packages directory"
  tags: npmrc
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.npm-packages"
    state: directory
    mode: "0755"
