---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: "Install system dependencies"
      ansible.builtin.apt:
        name:
          - sudo
        update_cache: true

    - name: "Create AccountsService icons directory"
      ansible.builtin.file:
        path: /var/lib/AccountsService/icons
        state: directory
        mode: "0755"
