---
- name: "Bottom | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: bottom

- name: "Bottom | Install Rust package with locked dependencies"
  become: true
  community.general.cargo:
    name: bottom
    state: latest
    locked: true
    path: "/usr/local"
  environment:
    RUSTUP_HOME: "{{ ansible_user_dir }}/.rustup"
    CARGO_HOME: "{{ ansible_user_dir }}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.cargo/bin"
  when: bottom_packages is not defined
  tags: bottom
  notify:
    - "Bottom | Install assets"

- name: "Bottom | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ bottom_packages }}"
    state: present
  when: bottom_packages is defined
  tags: bottom

- name: "Bottom | Copy configuration file"
  tags: bottom
  block:
    - name: "Bottom | Ensure configuration folder exists"
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/bottom"
        state: "directory"
        mode: "0755"
        recurse: true

    - name: "Bottom | Copy configuration file"
      ansible.builtin.copy:
        src: "bottom.toml"
        dest: "{{ ansible_user_dir }}/.config/bottom/bottom.toml"
        mode: "0644"
