---
- name: "Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags: bottom

- name: "Install Rust package with locked dependencies"
  community.general.cargo:
    name: bottom
    state: latest
    locked: true
  when: bottom_packages is not defined
  tags: bottom
  notify:
    - "Install bottom assets"

- name: "Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ bottom_packages }}"
    state: present
  when: bottom_packages is defined
  tags: bottom

- name: "Copy configuration file"
  tags: bottom
  block:
    - name: "Ensure configuration folder exists"
      ansible.builtin.file:
        path: "{{ ansible_facts.user_dir }}/.config/bottom"
        state: "directory"
        mode: "0755"
        recurse: true

    - name: "Copy configuration file"
      ansible.builtin.copy:
        src: "bottom.toml"
        dest: "{{ ansible_facts.user_dir }}/.config/bottom/bottom.toml"
        mode: "0644"
