---
- name: "Alacritty | Get latest version number"
  register: latest_json
  ansible.builtin.uri:
    url: "https://api.github.com/repos/alacritty/alacritty/releases/latest"
    method: GET
    return_content: true
    status_code: 200
    body_format: json

- name: "Alacritty | Set facts"
  ansible.builtin.set_fact:
    alacritty_latest_version: "{{ latest_json.json.tag_name[1:] }}"

- name: "Alacritty | Install desktop files and man pages"
  ansible.builtin.include_tasks: source-external.yml
  loop:
    - url: "https://github.com/alacritty/alacritty/releases/download/v{{ alacritty_latest_version }}/Alacritty.desktop"
      dest: "/usr/local/share/applications"
    - url: "https://github.com/alacritty/alacritty/releases/download/v{{ alacritty_latest_version }}/alacritty.1.gz"
      dest: "/usr/local/share/man/man1"
    - url: "https://github.com/alacritty/alacritty/releases/download/v{{ alacritty_latest_version }}/alacritty.5.gz"
      dest: "/usr/local/share/man/man5"
    - url: "https://github.com/alacritty/alacritty/releases/download/v{{ alacritty_latest_version }}/alacritty-msg.1.gz"
      dest: "/usr/local/share/man/man1"
    - url: "https://github.com/alacritty/alacritty/releases/download/v{{ alacritty_latest_version }}/alacritty-bindings.5.gz"
      dest: "/usr/local/share/man/man5"
    - url: "https://github.com/alacritty/alacritty/releases/download/v{{ alacritty_latest_version }}/_alacritty"
      dest: "/usr/local/share/zsh/site-functions"
    - url: "https://github.com/alacritty/alacritty/releases/download/v{{ alacritty_latest_version }}/alacritty.bash"
      dest: "/usr/local/share/bash-completion/completions"
      name: "alacritty"
    - url: "https://github.com/alacritty/alacritty/releases/download/v{{ alacritty_latest_version }}/alacritty.fish"
      dest: "/usr/local/share/fish/vendor_completions.d"
