---
- name: "Alacritty | Ensure directory exists: {{ item.dest | basename }}"
  become: true
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: directory
    mode: "0755"

- name: "Alacritty | Install {{ item.url | basename }}"
  become: true
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "0644"

- name: "Alacritty | Rename file"
  when: item.name is defined
  block:
    - name: "Alacritty | Copy file"
      ansible.builtin.copy:
        src: "{{ item.dest }}"
        dest: "{{ item.dest | dirname }}/{{ item.name }}"
        mode: "0644"

    - name: "Alacritty | Remove old file {{ item.dest }}"
      ansible.builtin.file:
        path: "{{ item.dest }}"
        state: "absent"
