---
- name: "Alacritty | Ensure directory exists: {{ item.destdir }}"
  become: true
  ansible.builtin.file:
    path: "{{ item.destdir }}"
    state: directory
    mode: "0755"

- name: "Alacritty | Install {{ item.url | basename }}"
  become: true
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.destdir }}/{{ item.url | basename }}"
    mode: "0644"

- name: "Alacritty | Rename file"
  become: true
  when: item.name is defined
  vars:
    oldfilepath: "{{ item.destdir }}/{{ item.url | basename }}"
    newfilepath: "{{ item.destdir }}/{{ item.name }}"
  block:
    - name: "Alacritty | Copy file"
      ansible.builtin.copy:
        src: "{{ oldfilepath }}"
        dest: "{{ newfilepath }}"
        mode: "0644"

    - name: "Alacritty | Remove old file {{ oldfilepath }}"
      ansible.builtin.file:
        path: "{{ oldfilepath }}"
        state: "absent"
