---

- name: "Check that it is supported by the OS"
  ansible.builtin.assert:
    that:
      - ansible_facts.system == "Linux"

- name: "Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags: owncloud_client

- name: "Add dependencies and repo"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: owncloud_client
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags: owncloud_client

- name: "Install packages"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ owncloud_client_packages }}"
  tags: owncloud_client

- name: "Copy service file"
  ansible.builtin.copy:
    src: "owncloud-client.service"
    dest: "{{ owncloud_client_service_dir }}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: "0644"
  notify: "Restart owncloud client service"
  tags: owncloud_client
