---
- name: "Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags: ghostty

- name: "Add repository [{{ ansible_facts.os_family }}]"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: ghostty
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags: ghostty

- name: "Install packages"
  become: true
  when: ghostty_packages is defined
  ansible.builtin.package:
    name: "{{ ghostty_packages }}"
    state: present
    update_cache: true
  tags: ghostty
  notify:
    - "Ghostty | Enable service"
    - "Ghostty | Start service"

- name: "Copy configuration"
  tags: ghostty
  block:
    - name: "Ensure configuration directory exists"
      ansible.builtin.file:
        path: "{{ ghostty_config_dir }}"
        state: "directory"
        mode: "0755"

    - name: "Copy Ghostty configuration files"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ ghostty_config_dir }}"
        mode: "0644"
      with_fileglob:
        - "{{ role_path }}/files/*.ghostty"

    - name: "Generate tab-style CSS file"
      ansible.builtin.command:
        cmd: "sassc -t expanded {{ role_path }}/files/tab-style.scss {{ ghostty_config_dir }}/tab-style.css"
      register: ghostty_sassc
      changed_when: ghostty_sassc.rc == 0
      failed_when: ghostty_sassc.rc != 0

- name: "Download themes"
  tags: ghostty
  block:
    - name: "Ensure theme directory exists"
      ansible.builtin.file:
        path: "{{ ghostty_themes_dir }}"
        state: "directory"
        mode: "0755"

    - name: "Copy Ghostty configuration files"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/catppuccin/ghostty/refs/heads/main/themes/catppuccin-{{ item }}.conf"
        dest: "{{ ghostty_themes_dir }}"
        mode: "0644"
        owner: "{{ ansible_facts.user_uid }}"
        group: "{{ ansible_facts.user_gid }}"
      loop:
        - frappe
        - latte
        - macchiato
        - mocha
