---
- name: "Discord | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags:
    - discord
    - messaging

- name: "Discord | Install from archive"
  ansible.builtin.include_tasks:
    file: "source.yml"
    apply:
      tags:
        - discord
        - messaging
  when: discord_packages is not defined
  tags:
    - discord
    - messaging

- name: "Discord | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ discord_packages }}"
    state: present
  when: discord_packages is defined
  tags:
    - discord
    - messaging
