---
- name: "Discord | Get latest version number"
  register: discord_latest_json
  ansible.builtin.uri:
    url: "{{ discord_version_url }}"
    method: GET
    return_content: true
    status_code: 200
    headers:
      Accept: application/json

- name: "Discord | Set latest version"
  ansible.builtin.set_fact:
    discord_latest_version: "{{ discord_latest_json.json.name }}"

- name: "Discord | Try to load version file"
  block:
    - name: "Discord | Load version file"
      ansible.builtin.set_fact:
        discord_version: "{{ lookup('file', discord_version_filepath) | from_json }}"

  rescue:
    - name: "Discord | Load version file [fallback]"
      ansible.builtin.set_fact:
        discord_version:
          version: "0.0.0"

- name: "Discord | Set current version"
  ansible.builtin.set_fact:
    discord_current_version: "{{ discord_version.version }}"

- name: "Discord | Install latest version [{{ discord_latest_version }}]"
  become: true
  when: "discord_current_version is ansible.builtin.version(discord_latest_version, '<')"
  block:
    - name: "Discord | Ensure final directory exist"
      ansible.builtin.file:
        path: "{{ discord_install_dir }}"
        state: directory
        owner: "root"
        group: "root"
        mode: "0755"

    - name: "Discord | Extract archive"
      ansible.builtin.unarchive:
        src: "{{ discord_apps_url }}/{{ ansible_facts['system'] | lower }}/{{ discord_latest_version }}/discord-{{ discord_latest_version
          }}.tar.gz"
        dest: "{{ discord_install_dir }}"
        owner: "root"
        group: "root"
        exclude:
          - "Discord/postinst.sh"
          - "Discord/discord.desktop"
        extra_opts:
          - --strip-components=1
        remote_src: true

    - name: "Discord | Copy desktop file"
      block:
        - name: "Discord | Ensure applications directory exist"
          ansible.builtin.file:
            path: "{{ ansible_user_dir }}/.local/share/applications"
            state: directory
            owner: "root"
            group: "root"
            mode: "0755"

        - name: "Discord | Copy desktop file"
          ansible.builtin.template:
            src: "discord.desktop.j2"
            dest: "{{ ansible_user_dir }}/.local/share/applications/discord.desktop"
            owner: "root"
            group: "root"
            mode: "0644"

    - name: "Discord | Write version in custom file"
      ansible.builtin.template:
        src: "version.j2"
        dest: "{{ discord_version_filepath }}"
        owner: "root"
        group: "root"
        mode: "0644"
