---
sway_packages:
  - sway
  - lxsession-gtk3
  - thunar
  - networkmanager
  # Screenshots
  - grim
  - slurp
  # Theming
  - nwg-look
  - capitaine-cursors
  - vimix-cursors
  - xcursor-comix
  - xcursor-themes
  - adw-gtk-theme
  - adapta-gtk-theme
  - arc-gtk-theme
  - arc-solid-gtk-theme
  - materia-gtk-theme
  - pop-gtk-theme
