---
sway_packages:
  - x11-wm/sway
  - x11-wm/lxsession
  - x11-fm/thunar
  - archivers/thunar-archive-plugin
  - net/networkmgr
  # Screenshots
  - x11/grim
  - x11/slurp
  - sysutils/seatd
  - graphics/drm-kmod
