---
lsp_servers_package:
  # - lua-language-server
  - nodejs-bash-language-server
lsp_servers_npm:
  - "@ansible/ansible-language-server"
  - "@microsoft/compose-language-service"
  - "typescript-language-server"
  - "vscode-langservers-extracted"
  - "vscode-markdown-languageserver"
  - "yaml-language-server"
lsp_servers_pip:
  - "basedpyright"
