---
- name: "Include OS specific variables"
  ansible.builtin.include_vars: "{{ ansible_facts.os_family | lower }}.yml"
  tags: swaync

- name: "Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ swaync_packages }}"
    state: "present"
  tags: swaync
  notify: "Enable and restart swaync service"

- name: "Get version"
  ansible.builtin.command:
    cmd: "swaync --version"
  register: swaync_version
  changed_when: swaync_version.rc != 0
  tags: swaync

- name: "Extract version"
  ansible.builtin.set_fact:
    swaync_current_version: "{{ swaync_version.stdout | regex_search('[0-9]+.[0-9]+.[0-9]+') }}"
  tags: swaync

- name: "Copy service file"
  ansible.builtin.template:
    src: "swaync.service.j2"
    dest: "{{ ansible_facts.user_dir }}/.config/systemd/user/swaync.service"
    mode: "0644"
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
  notify: "Enable and restart swaync service"
  tags: swaync

- name: "Install configuration files"
  tags: swaync
  notify: "Enable and restart swaync service"
  block:
    - name: "Ensure directories exists"
      ansible.builtin.file:
        path: "{{ swaync_config_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_facts.user_uid }}"
        group: "{{ ansible_facts.user_gid }}"

    - name: "Copy static configuration files"
      ansible.builtin.copy:
        src: "config/"
        dest: "{{ swaync_config_dir }}"
        mode: "preserve"
        directory_mode: "0755"
        owner: "{{ ansible_facts.user_uid }}"
        group: "{{ ansible_facts.user_gid }}"

    - name: "Copy dynamic configuration files"
      ansible.builtin.template:
        src: "config.json.j2"
        dest: "{{ swaync_config_dir }}/config.json"
        mode: "0644"
        owner: "{{ ansible_facts.user_uid }}"
        group: "{{ ansible_facts.user_gid }}"

    - name: "Download catppuccin theme"
      ansible.builtin.get_url:
        url: "https://cdn.jsdelivr.net/npm/@catppuccin/palette/css/catppuccin.css"
        dest: "{{ swaync_config_dir }}/themes"
        mode: "0644"
        owner: "{{ ansible_facts.user_uid }}"
        group: "{{ ansible_facts.user_gid }}"

    - name: "Generated CSS"
      ansible.builtin.command:
        cmd: "sassc -t expanded {{ role_path }}/files/style/style.scss {{ swaync_config_dir }}/style.css"
      register: swaync_sassc
      changed_when: swaync_sassc.rc == 0
      failed_when: swaync_sassc.rc != 0
