---
- name: "TMux | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
  tags: tmux

- name: "TMux | Install from package manager"
  become: true
  tags: tmux
  ansible.builtin.package:
    name: "{{ tmux_packages }}"
    state: present

- name: "TMux | Ensure config directories exists"
  tags: tmux
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ tmux_config_dir }}"
    - "{{ tmux_plugins_dir }}"

- name: "TMux | Copy static files in configuration directory"
  tags: tmux
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ tmux_config_dir }}"
    mode: "0644"

- name: "TMux | Download TMux plugins manager"
  tags: tmux
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ tmux_plugins_dir }}/{{ item.plugin_dir }}"
    version: "{{ item.version }}"
    force: true
  loop:
    - repo: "https://github.com/tmux-plugins/tpm"
      plugin_dir: "tpm"
      version: "v3.1.0"
    - repo: "https://github.com/catppuccin/tmux"
      plugin_dir: "tmux"
      version: "v1.0.2"
    - repo: "https://github.com/tmux-plugins/tmux-sensible"
      plugin_dir: "tmux-sensible"
      version: "master"
    - repo: "https://github.com/tmux-plugins/tmux-yank"
      plugin_dir: "tmux-yank"
      version: "master"
