---
- name: "Include OS specific variables"
  ansible.builtin.include_vars: "{{ ansible_facts.os_family | lower }}.yml"
  tags: waybar

- name: "Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ waybar_packages }}"
    state: "present"
  tags: waybar

- name: "Get version"
  ansible.builtin.command:
    cmd: "waybar --version"
  register: waybar_version
  changed_when: waybar_version.rc != 0
  tags: waybar

- name: "Extract version"
  ansible.builtin.set_fact:
    waybar_current_version: "{{ waybar_version.stdout | regex_search('[0-9]+.[0-9]+.[0-9]+') }}"
  tags: waybar

- name: "Install service file"
  tags: waybar
  block:
    - name: "Ensure directories exists"
      ansible.builtin.file:
        path: "{{ waybar_systemd_dir }}"
        state: "directory"
        mode: "0755"
        owner: "{{ ansible_facts.user_id }}"
        group: "{{ ansible_facts.user_gid }}"

    - name: "Copy service file"
      ansible.builtin.copy:
        src: "waybar.service"
        dest: "{{ waybar_systemd_dir }}/waybar-user.service"
        mode: "0644"
        owner: "{{ ansible_facts.user_id }}"
        group: "{{ ansible_facts.user_gid }}"
      notify:
        - "Restart 'waybar-user' service"

    - name: "Copy service file"
      ansible.builtin.file:
        path: "{{ waybar_systemd_dir }}/waybar.service"
        state: absent
      notify:
        - "Disable 'waybar' service"

- name: "Install configuration files"
  tags: waybar
  notify:
    - "Disable 'waybar' service"
    - "Restart 'waybar-user' service"
  block:
    - name: "Ensure directories exists"
      ansible.builtin.file:
        path: "{{ waybar_config_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_facts.user_id }}"
        group: "{{ ansible_facts.user_gid }}"

    - name: "Copy static configuration files"
      ansible.builtin.copy:
        src: "config/"
        dest: "{{ waybar_config_dir }}"
        mode: "preserve"
        directory_mode: "0755"
        owner: "{{ ansible_facts.user_id }}"
        group: "{{ ansible_facts.user_gid }}"

    - name: "Generated CSS"
      ansible.builtin.command:
        cmd: "sassc -t expanded {{ role_path }}/files/style.scss {{ waybar_config_dir }}/style.css"
      register: waybar_sassc
      changed_when: waybar_sassc.rc == 0
      failed_when: waybar_sassc.rc != 0

    - name: "Copy dynamic configuration files"
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ waybar_config_dir }}/{{ item }}"
        mode: "0644"
        owner: "{{ ansible_facts.user_id }}"
        group: "{{ ansible_facts.user_gid }}"
      loop:
        - sway.jsonc
        - hyprland.jsonc
        - modules.jsonc

- name: "Create virtualenv for Python scripts"
  ansible.builtin.pip:
    name: "{{ waybar_pip_packages }}"
    state: "present"
    virtualenv: "{{ waybar_config_dir }}/scripts/.venv"
  tags: waybar
