---
- name: "Oh My Posh | Install binary"
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v{{ oh_my_posh_version }}/posh-{{ ansible_system | lower }}-{{ alt_arch }}"
    dest: "/usr/local/bin/oh-my-posh"
    mode: "0755"
  tags:
    - oh_my_posh
    - shell

- name: "Oh My Posh | Ensure config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/oh-my-posh"
    state: directory
    mode: "0755"
  tags:
    - oh_my_posh
    - shell

- name: "Oh My Posh | Copy configuration file"
  ansible.builtin.copy:
    src: "config.omp.yaml"
    dest: "{{ ansible_user_dir }}/.config/oh-my-posh"
    mode: "0644"
  tags:
    - oh_my_posh
    - shell
