---
- name: "Wofi | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: wofi

- name: "Wofi | Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ wofi_packages }}"
    state: present
  tags: wofi

- name: "Wofi | Install configuration"
  tags: wofi
  block:
    - name: "Wofi | Ensure directory exist"
      ansible.builtin.file:
        path: "{{ wofi_config_dir }}"
        state: directory
        mode: "0755"

    - name: "Wofi | Copy configuration files"
      ansible.builtin.copy:
        src: "config"
        dest: "{{ wofi_config_dir }}/config"
        mode: "0644"

    - name: "Wofi | Generated CSS"
      ansible.builtin.command:
        cmd: "sassc -t expanded {{ role_path }}/files/style.scss {{ wofi_config_dir }}/style.css"
      register: swaync_sassc
      changed_when: swaync_sassc.rc == 0
      failed_when: swaync_sassc.rc != 0
