monitor.alsa.rules = [
  {
    matches = [
      {
		device.nick = "WD19 Dock"
      },
      {
		device.nick = "sof-soundwire"
      }
    ]
    actions = {
      update-props = {
          device.disabled = true
      }
    }
  }
]
