---
- name: "LightDM | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: lightdm

- name: "LightDM | Install package"
  become: true
  ansible.builtin.package:
    name: "{{ lightdm_packages }}"
    state: present
  tags: lightdm

- name: "LightDM | Copy configuration"
  become: true
  tags: lightdm
  block:
    - name: "LightDM | Ensure config directory exists"
      ansible.builtin.file:
        path: "{{ lightdm_config_path | ansible.builtin.dirname }}"
        state: directory
        mode: "0755"

    - name: "LightDM | Update configuration"
      ansible.builtin.template:
        src: "lightdm-gtk-greeter.conf.j2"
        dest: "{{ lightdm_config_path }}"
        owner: "root"
        group: "{{ root_primary_group | int }}"
        mode: "0644"
