---
- name: "Fastfetch | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: [discord, messaging]

- name: "Fastfetch | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ fastfetch_packages }}"
  when: fastfetch_packages is defined
  tags: fastfetch

- name: "Fastfetch | Install from sources"
  ansible.builtin.include_tasks:
    file: source.yml
    apply:
      tags: fastfetch
  when: fastfetch_packages is not defined
  tags: fastfetch

- name: "Fastfetch | Ensure config directory exists"
  ansible.builtin.file:
    path: "{{ fastfetch_config_dir }}"
    state: directory
    mode: "0755"
  tags: fastfetch

- name: "Fastfetch | Copy config file"
  ansible.builtin.template:
    src: "config.jsonc.j2"
    dest: "{{ fastfetch_config_dir }}/config.jsonc"
    mode: "0644"
  tags: fastfetch
