---
# tasks file for shell
- name: "Fastfetch | Install from sources"
  ansible.builtin.import_tasks: source-install.yml
  when: ansible_os_family == "Debian"

- name: "Fastfetch | Install from package manager"
  ansible.builtin.import_tasks: package-install.yml
  when: ansible_os_family != "Debian"

- name: "Fastfetch | Create symlink to config"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ fastfetch_config_dir }}"
    state: link
    force: true
