---
# tasks file for shell
- name: "Fastfetch | Install from sources"
  ansible.builtin.include_tasks:
    file: source-install.yml
    apply:
      tags: fastfetch
  when: ansible_os_family == "Debian"
  tags: fastfetch

- name: "Fastfetch | Install from package manager"
  ansible.builtin.include_tasks:
    file: package-install.yml
    apply:
      tags: fastfetch
  when: ansible_os_family != "Debian"
  tags: fastfetch

- name: "Fastfetch | Ensure config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/fastfetch"
    state: directory
    mode: "0755"
  tags: fastfetch

- name: "Fastfetch | Copy config file"
  ansible.builtin.template:
    src: "config.jsonc.j2"
    dest: "{{ ansible_user_dir }}/.config/fastfetch/config.jsonc"
    mode: "0644"
  tags: fastfetch
