---
laptops:
  hosts:
    t480:
      ansible_user: hbuyse
      ansible_host: 192.168.1.40
    latitude5400:
      ansible_user: henrib
      ansible_host: 192.168.1.6

towers:
  hosts:
    white-tower:
      ansible_user: hbuyse
      ansible_host: 192.168.1.30

localgroup:
  hosts:
    local:
      ansible_connection: local
      ansible_host: localhost
