---
- name: "CodeSpell | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: [codespell, formatter, formatters]

- name: "CodeSpell | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ codespell_packages }}"
    update_cache: true
    state: present
  tags: [codespell, formatter, formatters]
  when: codespell_packages is defined

- name: "CodeSpell | Install from source"
  ansible.builtin.include_tasks:
    file: "source.yml"
    apply:
      tags: [codespell, formatter, formatters]
  tags: [codespell, formatter, formatters]
  when: (codespell_packages is not defined) or codespell_force_source_install
