---
- name: "Mattermost Desktop | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      skip: true
  tags:
    - mattermost
    - messaging

- name: "Mattermost Desktop | Uninstall from Snap"
  become: true
  community.general.snap:
    name: "mattermost-desktop"
    state: absent
  tags:
    - mattermost
    - messaging

- name: "Mattermost Desktop | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ mattermost_desktop_packages }}"
    state: present
  tags:
    - mattermost
    - messaging
  when: mattermost_desktop_packages is defined

- name: "Mattermost Desktop | Install from source"
  ansible.builtin.include_tasks:
    file: "source.yml"
    apply:
      tags:
        - mattermost
        - messaging
  tags:
    - mattermost
    - messaging
  when: mattermost_desktop_packages is not defined
