---
- name: "Eza | Install Rust package with locked dependencies"
  become: true
  community.general.cargo:
    name: eza
    state: latest
    locked: true
    path: "/usr/local"
  environment:
    RUSTUP_HOME: "{{ ansible_user_dir }}/.rustup"
    CARGO_HOME: "{{ ansible_user_dir }}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.cargo/bin"
  notify: "Eza | Install completions and manpage"
