---
- name: "YamlFmt | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags:
    - yamlfmt
    - formatter

- name: "YamlFmt | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ yamlfmt_packages }}"
    state: present
  tags:
    - yamlfmt
    - formatter
  when: yamlfmt_packages is defined

- name: "YamlFmt | Install from source"
  ansible.builtin.include_tasks:
    file: "source.yml"
    apply:
      tags:
        - yamlfmt
        - formatter
  tags:
    - yamlfmt
    - formatter
  when: (yamlfmt_packages is not defined) or yamlfmt_force_source_install
