---
- name: "Docker | Install dependencies [Debian]"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ docker_dependencies }}"

- name: "Docker | Add deb repository - modern"
  when: ansible_version.full >= "2.15.0"
  ansible.builtin.include_tasks:
    file: debian-modern.yml
    apply:
      tags: docker

- name: "Docker | Add deb repository - legacy"
  when: ansible_version.full < "2.15.0"
  ansible.builtin.include_tasks:
    file: debian-legacy.yml
    apply:
      tags: docker
