---
- name: "Docker | Install repository [Debian]"
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release }}"
    components:
      - stable
    architectures:
      - "{{ deb_arch }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
