---
- name: "Docker | Download GPG key"
  become: true
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: "0644"

- name: "Docker | Add deb repository"
  become: true
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch={{ deb_arch }} signed-by=/etc/apt/keyrings/docker.asc] \
      https://download.docker.com/linux/{{ ansible_distribution | lower }} \
      {{ ansible_distribution_release }} stable"
    state: present
    update_cache: false
