---
- name: "Docker | Install dependencies [Debian]"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - ca-certificates

- name: "Docker | Install repository [Debian]"
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release }}"
    components:
      - stable
    architectures:
      - amd64
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

- name: "Docker | Install packages [Debian]"
  become: true
  ansible.builtin.package:
    update_cache: true
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  notify: "Docker | Restart docker service"
