---
- name: "Docker | Install dependencies [Debian]"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ docker_dependencies }}"

- name: "Docker | Install repository [Debian]"
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release }}"
    components:
      - stable
    architectures:
      - amd64
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
