---
- name: "Docker | Install [{{ ansible_distribution }}]"
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - docker

- name: "Docker | Install [{{ ansible_distribution }}]"
  ansible.builtin.import_tasks: archlinux.yml
  when: ansible_os_family == 'Archlinux'
  tags:
    - docker

- name: "Docker | Install [{{ ansible_distribution }}]"
  ansible.builtin.import_tasks: suse.yml
  when: ansible_os_family == 'Suse'
  tags:
    - docker
