---
- name: "Docker | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: docker


- name: "Docker | Add dependencies and repo"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: docker
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: docker

- name: "Docker | Install packages"
  become: true
  ansible.builtin.package:
    update_cache: true
    state: present
    name: "{{ docker_packages }}"
  notify: "Docker | Restart docker service"
  tags: docker

- name: "Docker | Ensure docker users are added to the docker group"
  become: true
  tags: docker
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
