---
- name: "Ensure directories exists"
  ansible.builtin.file:
    path: "{{ sway_config_dir }}"
    state: directory
    mode: "0755"

- name: "Copy configuration files"
  ansible.builtin.copy:
    src: "sway/"
    dest: "{{ sway_config_dir }}/"
    mode: "preserve"
    directory_mode: "0755"

- name: "Copy dynamic configuration files"
  ansible.builtin.template:
    src: "sway/{{ item }}.j2"
    dest: "{{ sway_config_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - variables
    - config.d/01-default-screen.conf
