---
- name: "Sway | Ensure directories exists"
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/sway"
    state: directory
    mode: "0755"

- name: "Sway | Copy configuration files"
  ansible.builtin.copy:
    src: "sway/"
    dest: "{{ ansible_facts['user_dir'] }}/.config/sway/"
    mode: "preserve"
    directory_mode: "0755"

- name: "Sway | Copy dynamic configuration files"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_facts['user_dir'] }}/.config/{{ item }}"
    mode: "0644"
  loop:
    - sway/variables
    - sway/config.d/01-default-screen.conf
