---
- name: "Copy sway-session and lxpolkit service files"
  ansible.builtin.copy:
    src: "service/{{ item }}"
    dest: "{{ ansible_facts.user_dir }}/.config/systemd/user"
    mode: "0644"
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
  loop:
    - "lxpolkit.service"
    - "sway-session.target"

- name: "Enable lxpolkit service"
  become: false
  ansible.builtin.systemd:
    name: "lxpolkit"
    daemon_reload: true
    enabled: true
    scope: "user"
  tags:
    - sway
    - lxpolkit
