---
# tasks file for sway
- name: "Sway | Install required packages [Suse]"
  ansible.builtin.include_tasks:
    file: suse.yml
  when: ansible_os_family == "Suse"

- name: "Sway | Install required packages [Archlinux]"
  ansible.builtin.include_tasks:
    file: archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: "Sway | Copy sway service file"
  ansible.builtin.copy:
    src: sway.service
    dest: /usr/local/lib/systemd/user/
    mode: "0644"
  become: true
  tags:
    - configure_files

- name: "Sway | Copy wayland-session file for sway"
  ansible.builtin.copy:
    src: sway.desktop
    dest: /usr/local/share/wayland-sessions
    mode: "0644"
  become: true
  tags:
    - configure_files

- name: "Sway | Copy sway-session target file"
  ansible.builtin.copy:
    src: sway-session.target
    dest: /usr/local/lib/systemd/user/
    mode: "0644"
  become: true
  tags:
    - configure_files

- name: "Sway | Copy sway-wrapper shell script"
  ansible.builtin.copy:
    src: sway-wrapper.sh
    dest: /usr/local/bin
    mode: "0755"
  become: true
  tags:
    - configure_files
