---
- name: "Mako | Disable 'dunst' service if exists"
  ansible.builtin.systemd:
    name: "dunst"
    enabled: false
    state: "stopped"
    scope: user
  when: "'dunst' in ansible_facts.services"

- name: "Mako | Restart service"
  ansible.builtin.systemd:
    name: "mako"
    state: "restarted"
    enabled: true
    scope: user
  when: "'swaync' not in role_names"

- name: "Mako | Disable and stop service"
  ansible.builtin.systemd:
    name: "mako"
    state: "stopped"
    enabled: false
    scope: user
  when: "'swaync' in role_names"
