---
- name: "Pre-tasks | Get dpkg architecture [Debian]"
  shell: dpkg --print-architecture
  register: deb_arch_tmp

- name: "Pre-tasks | Store DPKG architecture as fact [Debian]"
  ansible.builtin.set_fact:
    deb_arch: "{{ deb_arch_tmp.stdout }}"
