---
- name: "Pre-tasks | Define alternative architecture naming [Common]"
  ansible.builtin.set_fact:
    alt_arch: "{{ ansible_machine | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}"
  tags: always

- name: "Pre-tasks | Run some OS specific tasks [{{ ansible_os_family }}]"
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: always
  with_first_found:
    - files:
      - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: always
