---
- name: "RPM Fusion | Install repositories"
  become: true
  tags: rpmfusion
  block:
    - name: "RPM Fusion | Import GPG keys"
      ansible.builtin.rpm_key:
        key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-{{ repo }}-{{ ansible_facts.distribution
          | lower }}-2020"
        state: present
      loop:
        - "free"
        - "nonfree"
      loop_control:
        loop_var: repo

    - name: "RPM Fusion | Install repo package"
      ansible.builtin.dnf:
        name: "https://mirrors.rpmfusion.org/{{ repo }}/{{ ansible_facts.distribution | lower }}/rpmfusion-{{ repo }}-release-{{
          ansible_facts.distribution_major_version }}.noarch.rpm"
        state: present
      loop:
        - "free"
        - "nonfree"
      loop_control:
        loop_var: repo

- name: "Terra | Install repository"
  tags: "terra"
  block:
    - name: "Terra | Check if repository is installed"
      ansible.builtin.stat:
        name: "/etc/yum.repos.d/terra.repo"
      register: terra_repo_stat_result

    - name: "Terra | Install repo package"
      become: true
      ansible.builtin.command:
        cmd: >
          dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release
      when: not terra_repo_stat_result.stat.exists
