---
- name: "RPM Fusion | Install repo package"
  become: true
  ansible.builtin.dnf:
    name:
      "https://download1.rpmfusion.org/{{ repo }}/{{ ansible_distribution | lower }}/rpmfusion-{{ repo }}-release-\
      {{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  loop:
    - "free"
    - "nonfree"
  loop_control:
    loop_var: repo
  tags: rpmfusion
