---
- name: "StyLua | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags: [stylua, formatter]

- name: "StyLua | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ stylua_packages }}"
    update_cache: true
    state: present
  tags: [stylua, formatter]
  when: stylua_packages is defined

- name: "StyLua | Install Rust package with locked dependencies"
  become: true
  community.general.cargo:
    name: stylua
    state: latest
    locked: true
    path: "/usr/local"
  environment:
    RUSTUP_HOME: "{{ ansible_user_dir }}/.rustup"
    CARGO_HOME: "{{ ansible_user_dir }}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.cargo/bin"
  tags: [stylua, formatter]
  when: stylua_packages is not defined
