---
- name: "StyLua | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags:
    - stylua
    - formatter

- name: "StyLua | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ stylua_packages }}"
    state: present
  tags:
    - stylua
    - formatter
  when: stylua_packages is defined

- name: "StyLua | Install Rust package with locked dependencies"
  community.general.cargo:
    name: stylua
    state: latest
    locked: true
  tags:
    - stylua
    - formatter
  when: (stylua_packages is not defined) or stylua_force_source_install
