---
- name: "StyLua | Get latest version number"
  register: latest_json
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ stylua_github_user }}/{{ stylua_github_repo }}/releases/latest"
    method: GET
    return_content: true
    status_code: 200
    body_format: json

- name: "StyLua | Set facts"
  ansible.builtin.set_fact:
    stylua_latest_version: "{{ latest_json.json.tag_name[1:] }}"

- name: "StyLua | Install executable"
  become: true
  ansible.builtin.unarchive:
    src:
      "https://github.com/{{ stylua_github_user }}/{{ stylua_github_repo }}/releases/download/v{{ stylua_latest_version }}/\
      stylua-{{ ansible_system }}-{{ ansible_architecture }}.zip"
    dest: "/usr/local/bin"
    mode: "0755"
    include:
      - "stylua"
    remote_src: true
