---
- name: "Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags: swayidle

- name: "Install packages"
  become: true
  ansible.builtin.package:
    name: "{{ swayidle_packages }}"
    state: present
  tags: swayidle

- name: "Install configuration"
  tags: swayidle
  block:
    - name: "Ensure directory exist"
      ansible.builtin.file:
        path: "{{ swayidle_config_dir }}"
        state: directory
        mode: "0755"

    - name: "Copy configuration"
      ansible.builtin.copy:
        src: "config"
        dest: "{{ swayidle_config_dir }}"
        mode: "0644"
      notify: "Enable and restart swayidle service"

- name: "Install service file"
  tags: swayidle
  block:
    - name: "Ensure directory exist"
      ansible.builtin.file:
        path: "{{ swayidle_service_dir }}"
        state: directory
        mode: "0755"

    - name: "Copy service file"
      ansible.builtin.copy:
        src: "swayidle.service"
        dest: "{{ swayidle_service_dir }}"
        mode: "0644"
      notify: "Enable and restart swayidle service"
