---
- name: "Alacritty | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags:
    - alacritty

- name: "Alacritty | Install from source [{{ ansible_os_family }}]"
  ansible.builtin.include_tasks:
    file: source.yml
    apply:
      tags: alacritty
  when: alacritty_packages is not defined
  tags:
    - alacritty

- name: "Alacritty | Install from package manager [{{ ansible_os_family }}]"
  ansible.builtin.include_tasks:
    file: package.yml
    apply:
      tags: alacritty
  when: alacritty_packages is defined
  tags:
    - alacritty

- name: "Alacritty | Ensure config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/alacritty"
    state: directory
    mode: "0755"
  tags:
    - alacritty

- name: "Alacritty | Copy static files in configuration directory"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_user_dir }}/.config/alacritty"
    mode: "0644"
  tags:
    - alacritty

- name: "Alacritty | Install catppuccin themes"
  ansible.builtin.git:
    repo: "https://github.com/alacritty/alacritty-theme"
    dest: "{{ ansible_user_dir }}/.config/alacritty/themes"
    version: "master"
  tags:
    - alacritty
