---
- name: "Restart service"
  block:
    - name: "Disable 'waybar' service"
      ansible.builtin.systemd:
        name: "waybar.service"
        enabled: false
        state: "stopped"
        scope: "user"

    - name: "Restart 'waybar-user' service"
      ansible.builtin.systemd:
        name: "waybar-user.service"
        enabled: true
        state: "restarted"
        scope: "user"
