---
- name: Install cargo executables
  hosts: localhost
  tasks:
    - name: Install Rust packages
      community.general.cargo:
        name:
          - ripgrep
          - bottom
          - fd-find
          - stylua
          - du-dust
          - git-delta
          - alacritty
          - zoxide
          - gitui
          - eza
          - bat
