---
- name: "Bitwarden Desktop | Get latest version number"
  register: bitwarden_releases_json
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ bitwarden_owner }}/{{ bitwarden_repo }}/releases"
    method: GET
    return_content: true
    status_code: 200
    body_format: json
  tags: bitwarden

- name: "Bitwarden Desktop | Set facts"
  ansible.builtin.set_fact:
    bitwarden_desktop_latest_tag: "{{ (bitwarden_releases_json.json | selectattr('tag_name', 'search', '^desktop') | first).tag_name
      }}"
    bitwarden_desktop_latest_version: "{{ (bitwarden_releases_json.json | selectattr('tag_name', 'search', '^desktop') | first).tag_name[9:]
      }}"
  tags: bitwarden

- name: "Bitwarden Desktop | Install man pages"
  ansible.builtin.get_url:
    url: "https://github.com/{{ bitwarden_owner }}/{{ bitwarden_repo }}/releases/download/{{ bitwarden_desktop_latest_tag
      }}/Bitwarden-{{ bitwarden_desktop_latest_version }}-{{ ansible_facts['architecture'] }}.AppImage"
    dest: "{{ ansible_user_dir }}/.local/bin/bitwarden"
    mode: "0755"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_facts['user_gid'] }}"
  tags: bitwarden

- name: "Bitwarden Desktop | Install desktop file"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/bitwarden/clients/refs/heads/main/apps/desktop/resources/com.bitwarden.desktop.desktop"
    dest: "{{ ansible_user_dir }}/.local/share/applications/"
    mode: "0644"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_facts['user_gid'] }}"
  tags: bitwarden
