---
- name: "Enable ghostty service"
  ansible.builtin.systemd:
    service: "app-com.mitchellh.ghostty"
    enabled: true
    daemon_reload: true
    scope: "user"

- name: "Start ghostty service"
  ansible.builtin.systemd:
    service: "app-com.mitchellh.ghostty"
    state: "restarted"
    daemon_reload: true
    scope: "user"
