---
- name: "Tombi | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags:
    - tombi
    - lsp
    - formatter
    - linter

- name: "Tombi | Install from package manager"
  become: true
  when: tombi_package is defined
  ansible.builtin.package:
    name: "{{ tombi_package }}"
    state: present
  tags:
    - tombi
    - lsp
    - formatter
    - linter

- name: "Tombi | Install from Node Package Manager"
  when: tombi_package is not defined
  community.general.npm:
    name: "{{ tombi_npm_package }}"
    global: true
    state: latest
    production: true
    no_optional: true
  tags:
    - tombi
    - lsp
    - formatter
    - linter
