---
# tasks file for nvim
- name: "Neovim | Install program from package manager"
  become: true
  ansible.builtin.package:
    name:
      - neovim
    state: present
  when: ansible_distribution != "Ubuntu"

- name: "Neovim | Install program from static binary"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/download/v{{ nvim_version }}/nvim-linux64.tar.gz"
    dest: "/usr/local"
    remote_src: true
    extra_opts:
      - --strip-components=1
  when: ansible_distribution == "Ubuntu"

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ nvim_config_dir }}"
    state: directory

- name: "Neovim | Copy static files in configuration directory"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ nvim_config_dir }}"

- name: "Neovim | Copy templates files in configuration directory"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ nvim_config_dir }}/{{ item }}"
  loop:
    - "lua/hbuyse/plugins/formatter.lua"
    - "lua/hbuyse/init.lua"

- name: "Neovim | Sync plugins"
  ansible.builtin.command: nvim --headless "+Lazy! sync" +qa
