---
# tasks file for nvim
- name: "Neovim | Install program from package manager"
  become: true
  ansible.builtin.package:
    name:
      - neovim
    state: present
  when: ansible_distribution != "Ubuntu"

- name: "Neovim | Install program from static binary"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/download/v{{ nvim_version }}/nvim-linux64.tar.gz"
    dest: "/usr/local"
    remote_src: yes
    extra_opts:
      - --strip-components=1
  when: ansible_distribution == "Ubuntu"

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true

- name: "Neovim | Sync plugins"
  ansible.builtin.command: nvim --headless "+Lazy! sync" +qa
