---
- name: "FD | Include OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.os_family | lower }}.yml"
      skip: true
  tags: fd

- name: "FD | Install from package manager"
  become: true
  ansible.builtin.package:
    name: "{{ fd_packages }}"
    state: present
  tags: fd
  when: fd_packages is defined

- name: "FD | Install Rust package with locked dependencies"
  community.general.cargo:
    name: fd-find
    state: latest
    locked: true
  tags: fd
  when: fd_packages is not defined
