---
- name: "Bat | Install from source"
  ansible.builtin.include_tasks:
    file: source.yml
    apply:
      tags: bat
  when: ansible_os_family not in ['Archlinux', 'Suse']
  tags: bat

- name: "Bat | Install from package manager"
  ansible.builtin.include_tasks:
    file: package.yml
    apply:
      tags: bat
  when: ansible_os_family in ['Archlinux', 'Suse']
  tags: bat

- name: "Bat | Copy configuration file"
  tags: bat
  block:
    - name: "Bat | Ensure configuration folder exists"
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/bat"
        state: "directory"
        mode: "0755"
        recurse: true

    - name: "Bat | Copy configuration file"
      ansible.builtin.copy:
        src: "config"
        dest: "{{ ansible_user_dir }}/.config/bat"
        mode: "0644"

- name: "Bat | Install catppuccin themes"
  tags: bat
  block:
    - name: "Bat | Ensure themes folder exists"
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/bat/themes"
        state: "directory"
        mode: "0755"
        recurse: true

    - name: "Bat | Download catppuccin themes"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/catppuccin/bat/refs/heads/main/themes/Catppuccin%20{{ item | title }}.tmTheme"
        dest: "{{ ansible_user_dir }}/.config/bat/themes/catppuccin-{{ item }}.tmTheme"
        mode: "0644"
      loop:
        - frappe
        - mocha
        - latte
        - macchiato
      notify: "Bat | Rebuild cache"
