---
- name: "Tree-Sitter | Install Rust package with locked dependencies"
  community.general.cargo:
    name: "{{ treesitter_cargo_package }}"
    state: latest
    locked: true
  when: treesitter_packages is not defined
  tags: treesitter
